### PR TITLE
Allow plugins to set the parent/predecessor of a new session

### PR DESCRIPTION
**Pull request by MisterTea**
To support HTM ( see https://github.com/MisterTea/hyper-htm/issues/1 ), we need to be able to open sessions based on the ID of their parent (either the tab preceding the inserted tab or the split pane preceding the new split pane) instead of based on which one is active.  This PR parameterizes the session create functions to allow that.

### CODE REVIEW

**Comment by MisterTea** [comment]
ping

**Comment by MisterTea** [comment]
@chabou Can you take a look?  Thanks

**Comment by MisterTea** [comment]
@juancampa can you take a look?

**Comment by MisterTea** [comment]
Any update on this? @juancampa @chabou

**Comment by Stanzilla** [comment]
@MisterTea so sorry that I have been ignoring this (no idea what the others are up to), can you explain what HTM is?

**Comment by MisterTea** [comment]
@Stanzilla HTM is a way to use multiple tabs with a single SSH or ET connection. Here's a video showing how it works: https://youtu.be/Ea6Y08tP-RI

If you have ever used tmux, HTM is like that but with hooks into the terminal emulator so we can use your scrollbars and tabs instead of drawing our own in curses

**Comment by Stanzilla** [comment]
Alright, cool. Can you rebase your work then please?

**Comment by Stanzilla** [comment]
Thanks!

**Comment by MisterTea** [comment]
Cool, thanks!

**Pull request merged**
