### PR TITLE
Build 32 and 64 bit Linux builds

### PR DESCRIPTION
**Pull request by fearphage**
I can't test this, because I can't get this to run locally due to a host of failures and errors during the build process. 

Maybe you can?

### CODE REVIEW

**Comment by fearphage** [comment]
The goal was to fix #799. I'm not sure what the next steps are here.

**Comment by rauchg** [comment]
This is a very good call

**Comment by fearphage** [comment]
@rauchg Does it do whatever it's supposed to?

**Comment by rauchg** [comment]
@fearphage let's see!

**Pull request merged**
