### PR TITLE
Use the same accelerator as iterm for navigation between split panes

### PR DESCRIPTION
**Pull request by spirosikmd**
This fixes `Cmd+] and Cmd+[ navigates among split panes in order of use` in #828. Should be ready to be merged, but I am not sure if the linux accelerator is the ideal one, can you please verify this?

### CODE REVIEW

**Comment by ekmartin** [comment]
The reason we didn't use Cmd+][ in the first place wasn't technical, if I remember correctly it was because it doesn't really work on European keyboards where you don't have a specific key for [ and ]. I agree that Cmd+Alt+Tab isn't as convenient as it should be though, but we already use Cmd+Tab for cycling between tabs.

**Comment by spirosikmd** [comment]
It is your call guys. I still believe that using (in most cases) the default iterm shortcuts would be really useful. I know most (if not all) of my colleagues use iterm. Also those who don't have the english keyboard, they do change to an english keyboard layout while writing code. Which solves the issue in the first place.

**Comment by kleinfreund** [comment]
> they do change to an english keyboard layout while writing code.

Switching keyboard layouts is not solving the issue at hand, it's a mere workaround.

**Comment by MartinDelille** [comment]
+1 for *iTerm* shortcut. I personnaly have a AZERTY physical keyboard but I switch to QWERTY layout when writing code and using the terminal. 

Some people think it's crazy but I think they don't realize the confort it brings!

**Comment by spirosikmd** [comment]
Closing this PR as a similar [plugin](https://github.com/chabou/hyper-pane) has been made.

**Pull request closed without merging**
