### PR TITLE
Fix linting

### PR DESCRIPTION
**Pull request by paulcbetts**
Fix linting errors on master. This PR also reorders the ternary condition so that it is easier to understand. https://github.com/zeit/hyper/pull/1360/files?w=1 will show the non-whitespace changes

### CODE REVIEW

**Comment by chabou** [comment]
There's no linting errors on master. Just execute `yarn`befor launching tests.

**Comment by paulcbetts** [comment]
@chabou There is something wrong with the linter. On my machine on master:

```
  lib\components\tabs.js:32:11
  ×  32:11  Expected indentation of 8 spaces but found 10.   indent
  ×  33:13  Expected indentation of 10 spaces but found 12.  indent
  ×  54:13  Expected indentation of 10 spaces but found 12.  indent
  ×  59:11  Expected indentation of 8 spaces but found 10.   indent

  4 errors
```

On CI, with this PR:

```
  lib\components\tabs.js:32:9
  ×  32:9   Expected indentation of 10 spaces but found 8.   indent
  ×  33:11  Expected indentation of 12 spaces but found 10.  indent
  ×  54:11  Expected indentation of 12 spaces but found 10.  indent
  ×  59:9   Expected indentation of 10 spaces but found 8.   indent
  4 errors
npm ERR! Windows_NT 6.3.9600
```

**Comment by chabou** [comment]
execute `yarn` on your machine then `yarn run test`. Everything will be ok I think.

**Comment by paulcbetts** [comment]
@chabou Why in the world would running yarn vs npm make a difference

**Comment by chabou** [comment]
Maybe `npm install`is ok too, I don't know.
I had same linting error than you.
I launched `yarn`and some packages was installed/updated: no more linting error.

**Comment by paulcbetts** [comment]
@chabou Fair enough, I'll try :fire:ing my npm packages and rerunning

**Comment by paulcbetts** [comment]
Nope. Still broken. Running on a clean checkout gives me the same errors (after I nerf the thousands of linebreak-style errors)

Running with yarn gives me a _different_ set of errors:

```
  app\system-context-menu.js:1:26
  ×   1:26  Unable to resolve path to module winreg.                     import/no-unresolved

  app\notify.js:4:23
  ×   4:23  Unable to resolve path to module electron-is-dev.            import/no-unresolved

  app\session.js:5:30
  ×   5:30  Unable to resolve path to module default-shell.              import/no-unresolved
  ×  15:19  Unable to resolve path to module pty.js.                     import/no-unresolved

  app\plugins.js:7:24
  ×   7:24  Unable to resolve path to module electron-config.            import/no-unresolved
  ×   9:26  Unable to resolve path to module shell-env.                  import/no-unresolved

  app\config.js:7:23
  ×   7:23  Unable to resolve path to module electron-is-dev.            import/no-unresolved
  ×   8:22  Unable to resolve path to module gaze.                       import/no-unresolved
  ×   9:24  Unable to resolve path to module electron-config.            import/no-unresolved

  app\index.js:11:21
  ×  11:21  Unable to resolve path to module electron-squirrel-startup.  import/no-unresolved
  ×  17:21  Unable to resolve path to module electron-squirrel-startup.  import/no-unresolved
  ×  22:19  Unable to resolve path to module electron-squirrel-startup.  import/no-unresolved
  ×  33:31  Unable to resolve path to module git-describe.               import/no-unresolved
  ×  35:31  Unable to resolve path to module file-uri-to-path.           import/no-unresolved
  ×  36:23  Unable to resolve path to module electron-is-dev.            import/no-unresolved
```

**Comment by rauchg** [comment]
I *think* the confusion is that I fixed this already? Cause I ran into it last night. Should be good now. Thanks @paulcbetts

**Comment by paulcbetts** [comment]
@rauchg Yep, confirmed fixed now, thanks

**Pull request closed without merging**
