### PR TITLE
Nw/pty fixes

### PR DESCRIPTION
**Pull request by nw**
Should be good to go. An update to the`README.md` might be advised but will wait for feedback before proceeding.

* `pty.js` has been renamed to [node-pty](https://www.npmjs.com/package/node-pty) changes already made in [vscode](https://github.com/Microsoft/vscode/pull/18250/files). 
* Some of the build issues and troubleshooting are masked by [script/install](https://github.com/Tyriar/node-pty/blob/master/scripts/install.js). No handling of `stderr` also `spawn` should probably be used instead of `exec` or at the very least increase [maxBuffer](https://nodejs.org/api/child_process.html#child_process_maxbuffer_and_unicode). Going to issue a PR shortly.
* `node-gyp` builds can fail because of `xcode-select`. The following solution works great if you don't want to wait for a huge download from apple. http://stackoverflow.com/a/17980786 (`sudo xcode-select -s /Applications/Xcode.app/Contents/Developer`)
* Not a huge fan of how `install-app-deps` works. [#5 in quick setup](https://github.com/electron-userland/electron-builder#quick-setup-guide) references [node-gyp-rebuild](https://github.com/electron/electron-rebuild) which I found to be more intuitive, I refrained from adding an additional dep for now. Example: `electron-rebuild -m app -w node-pty`.
* Added `npm run clean` to reset everything for sanity checking.

cc: @rauchg

### CODE REVIEW

**Comment by rauchg** [comment]
> node-gyp builds can fail because of xcode-select. The following solution works great if you don't want to wait for a huge download from apple. http://stackoverflow.com/a/17980786 (sudo xcode-select -s /Applications/Xcode.app/Contents/Developer)

We should mention this on the README in the pty section

**Comment by Tyriar** [comment]
@nw you beat me to it! :smile: 

@rauchg FYI I gave up on doing this change because I couldn't build due to https://github.com/zeit/hyper/issues/1310

**Comment by rauchg** [comment]
@Tyriar strange, yet it works on Travis CI (Linux)? ¯\_(ツ)_/¯

**Comment by Tyriar** [comment]
Not sure why, it happened on both my Ubuntu 16.10 machines. I didn't try yarn though

**Pull request merged**
