### PR TITLE
Fix AVA tests and made them mandatory.

### LINKED ISSUE #2703: Fix unit tests and make them mandatory
Unit tests are using `ava`. There is some tests in our project. But running them are not mandatory to push a branch or to CI build. And now they are broken in our canary branch.

Please fix/remove outdated tests and make them mandatory

### PR DESCRIPTION
**Pull request by Ameya05**
Removed obsolete test cases and included unit tests a mandatory step while build and push.

Fixed #2703

### CODE REVIEW

**Comment by chabou** [comment]
Best thing is tests are now mandatory and I'll never brake them again :trollface:

**Comment by chabou** [comment]
@Ameya05 Thank you a lot for this PR 🙏

**Comment by Xapphire13** [comment]
@chabou, these changes have existed in this pr https://github.com/zeit/hyper/pull/2459 for 3 months now...

**Comment by chabou** [comment]
@Xapphire13 Sorry for that. But restoring test what not your PR main goal.
I can't merge your PR without hardcore reviewing/testing it.
But I could merge this one.

Keep in mind that is always better to have little PR that address only one issue.

But I feel really sorry to have your PR unreviewed since 3 months... 😞

**Comment by Xapphire13** [comment]
@chabou
I understand that. My issue is that you stopped replying to all correspondence on the pull request entirely (from me and other members of the community). As for testing, it's a very small change (with UTs) that should be easy to test in a short period of time.

**Pull request merged**
