### PR TITLE
Upgrade xterm to 3.7.0 Refs: #3178

### PR DESCRIPTION
**Pull request by xbtsw**
#2697 and #2793 both need a new version of xterm, and 3.7.0 just got released.

### CODE REVIEW

**Comment by omgaz** [comment]
Also closes #3178

**Comment by jocull** [comment]
This one should take precedence over #3178 👍

**Comment by JCMais** [comment]
Awesome, thank you @xbtsw

**Comment by xbtsw** [comment]
@albinekb There's no merge button available for me. Please kindly merge.

**Comment by dcalhoun** [comment]
Would love to see this merged and published, as it will fix issues like facebook/jest#6494.

**Comment by chabou** [comment]
Yes, we need to merge this ASAP.

**Comment by c-bandy** [comment]
What is the status on this?

**Comment by albinekb** [comment]
Waiting on someone else to approve, then we can merge. I have tested on macOS 10.12 and it works as expected.

**Comment by c-bandy** [comment]
Can someone take a look at this? It's one line to approve :sweat:

**Comment by chabou** [comment]
Thank you for your help @xbtsw :pray: 

I'm am really sorry but this PR won't be merged 😞
Every `xterm` new version comes with some minor changes that should be addressed.
Due to the lack of real automatic tests in `Hyper`, updating `xterm` must be manually and heavily tested. 

Closed in favor of https://github.com/zeit/hyper/pull/3255

**Pull request closed without merging**
