### PR TITLE
Add border radius to lib/component/notification.js

### PR DESCRIPTION
**Pull request by davidbarsky**
It's a small one liner; added a border radius to the `lib/component/notification.js`. I think it looks slightly friendlier, but feel free to disregard. Screenshot below:

screen shot 2016-10-16 at 11 35 15 am

### CODE REVIEW

**Comment by leo** [comment]
Maybe even `3px`?

**Comment by davidbarsky** [comment]
Maybe, yeah. It’s really a matter of personal taste. I tried 3px, but it seemed too rounded for me. Up to you! 😄

**Comment by leo** [comment]
@davidbarsky Can you share a screenshot with 3px?

**Comment by rauchg** [comment]
I'm also still not 100% sold on the contrast

**Comment by davidbarsky** [comment]
Hmm, makes sense.

Trouble is, I'm not sure how to summon the notification—I edited it in the Dev Tools when the update prompt showed up.

I'd be very happy to provide a comparison, but would appreciate advice on pulling up the notification on demand.

**Comment by expenses** [comment]
The notification was pretty hard to see with my brightness. Maybe change the text colour to black?

**Comment by matheuss** [comment]
cc @CodeTheory

**Comment by CodeTheory** [comment]
@rauchg we updated the contrast, but it hasn't been implemented yet. 
image

And you said yes to that. 😛

**Comment by rauchg** [comment]
@codetheory that looks great

**Comment by leo** [comment]
We can add more improvements to the notification UI in separate PRs! 🙏

**Comment by CodeTheory** [comment]
@leo Now that I have more time, I'm going to take a look into it myself.

**Pull request merged**
