### PR TITLE
readme es-Es

### PR DESCRIPTION
**Pull request by leovafme**

### CODE REVIEW

**Comment by albinekb** [comment]
Cool!

- Do we really want this?
-  How will we manage to update it to keep it inline with the "real" readme?

Maybe it's better to tell the person to use google translate? :D

**Comment by chabou** [comment]
Agree.
Maybe a link to separated self-hosted website (matained by another team) and with a disclamer (maybe not up-to-date) ?

**Comment by leovafme** [comment]
Go to google overload is more tedious, you can add a link in the documentation that leads to the translations and the documentation is just the start since to hyper terminal we would add multi language :)

**Comment by albinekb** [comment]
We won't be able to support this, the english documentation is already outdated. You could make a separate repo at your github and we could link it in the readme as unofficial-docs.

Thanks anyways!

**Pull request closed without merging**
