### PR TITLE
Fix unicode display, third attempt :\

### PR DESCRIPTION
**Pull request by tibotiber**
This is a follow up PR to #1536. It reverts the revert of the merge, and fixes the "includes of undefined" issue that appeared after running `dist`. Since I cannot reproduce the issue locally, it is a blind fix, please check on your side before merging ;).
Cc @albinekb @rauchg

### CODE REVIEW

**Comment by tibotiber** [comment]
Added a quick fix for #1506.

Before:
before

After:
after

**Comment by albinekb** [comment]
@tibotiber
>Uncaught DOMException: Failed to execute 'appendChild' on 'Node': This node type does not support this method.

**Comment by tibotiber** [comment]
@albinekb Can you try again? Sorry, it's kinda unpractical as I'm not able to test myself.

I changed `wrapUnicode` to replace text nodes by span elements if it needs to append children.

**Comment by albinekb** [comment]
Will do, but I wonder why this isn't happening to you 😱

**Comment by albinekb** [comment]
Inserting an emoji: image

but when i press space after the emoji:
image

🤔

**Comment by tibotiber** [comment]
@albinekb Thanks for your help with testing. I finally found how to reproduce the error. I had to remove `hyperlinks` from my plugins 😓. Tried your locales and envs settings but that didn't change anything. Glad I manage to reproduce anyway, it makes things much easier for debugging 😄. 

I believe I fixed the issue now. Since the previous commit, `wrapUnicode` may reassign the node it was given and return it, so the calling site needs to update the node with the returned value. This was done properly but I missed that the node was also needed to be reassigned to `this.cursorNode_`. Hence the `cursorNode_` was left out of updates. It is fixed now.

Hope we're good soon (c'mon, I can do this 😛).

**Comment by albinekb** [comment]
It's getting there! kapture 2017-05-28 at 23 06 13

Now i can type emojis, but seems like the width is not correct? When i type something after an emoji (another emoji, space, character etc) it breaks 🤔

**Comment by schmittyjd** [comment]
Will this pr also fix issues rendering powerline fonts?

**Comment by tibotiber** [comment]
@schmittyjd yes powerline fonts rendering will be fixed

@albinekb 
- the width of emojis is correct, it is in line with how iTerm and Terminal handle it, see [this comment](https://github.com/zeit/hyper/pull/1536#issuecomment-280816134) from @rauchg 
- for the emoji inputs, there are still some issues yes. I ignored them since it is also present in master. See examples below:

zsh before:
zsh-before

zsh after:
zsh-after

bash before:
bash-before

bash after:
bash-after

What do you think?

**Comment by tibotiber** [comment]
@albinekb friendly ping: any opinion about the issues for unicode input? Seems kind of independent from this PR to me, although the behaviour changes from bad to bad 🤔. Could it be addressed in a subsequent PR?

PS: VS Code moving forward with this too apparently: https://twitter.com/tyriar/status/870346230911483908 and they are on xterm

**Comment by tibotiber** [comment]
ping: what is the status with this? are we proceeding or dropping it for the upcoming switch to xterm?

**Comment by AndrewSB** [comment]
+1

would love an update on this too!

**Comment by LitoMore** [comment]
xterm +1

**Comment by Stanzilla** [comment]
@tibotiber Wanna close this? Or is anything in this PR still needed on `canary` after the switch to xterm?

**Comment by albinekb** [comment]
@tibotiber thanks for attempting to fix this 🙏 As we have moved away from the problematic `hterm` lib, I'm closing this PR here. Again, thanks for your efforts and hope you (I did!) learned something by doing this.

**Comment by chabou** [comment]
@tibotiber Really sorry and thank you so much for your help 🙏

**Comment by tibotiber** [comment]
@albinekb @chabou thanks for the kind message and no worries, what's important is that we've got hyper in a better shape now. At the very least i've learnt why we're moving to `xterm`, `hterm` was indeed problematic 😅. The work on these few PRs has been interesting anyway :). Cheers and keep the great work on hyper and more.

**Pull request closed without merging**
