### PR TITLE
use electron notification api

### PR DESCRIPTION
**Pull request by LabhanshAgrawal**
Using the Electron [Notification](https://www.electronjs.org/docs/api/notification) API

removes
https://github.com/zeit/hyper/blob/a6ba442c1d3f84096df0f978ebabb61f9096a7ba/app/notify.ts#L7
😜

### CODE REVIEW

**Comment by LabhanshAgrawal** [comment]
I tested it with mac and windows
Can someone please check it once with linux also.

**Comment by bet4it** [comment]
When will the notification happen?

**Comment by LabhanshAgrawal** [comment]
changing the config or even just saving it again should trigger a notification.

**Comment by bet4it** [comment]
Before:
before
After:
after

**Comment by LabhanshAgrawal** [comment]
I see, it was same for mac and windows, but that might be because these two os add the icon to the notification themselves.
Can you try this branch https://github.com/LabhanshAgrawal/hyper/tree/notif2
If that looks ok, then we can add a process.platform check to add icon for linux (on mac it gives two icons if enabled)

**Comment by bet4it** [comment]
Yes, that works.

**Comment by LabhanshAgrawal** [comment]
It looks the same? because on mac the icon from this comes on the right.

**Comment by bet4it** [comment]
Yes, the same as before.

**Comment by LabhanshAgrawal** [comment]
Nice, thanks for testing it, will update it.

**Comment by bet4it** [comment]
Not totally the same, in fact😅
notif

**Comment by LabhanshAgrawal** [comment]
Did you have some custom icon perhaps? The hyper icon should be the round(er) one.

**Comment by bet4it** [comment]
It seems that the icon before was added by Linux, which was specified in [PKGBUILD](https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=hyper-git).
After your commit the icon was obtained from itself.

**Comment by LabhanshAgrawal** [comment]
Seems like it's older icon taken from [here](https://github.com/zeit/art/blob/master/hyper/mark/Hyper-Mark-120%403x.png)

**Comment by LabhanshAgrawal** [comment]
Shouldn't be an issue. I've pushed again with the changes.
How can we get the icon in AUR updated?

**Comment by bet4it** [comment]
Why @zeit not update their https://github.com/zeit/art repository😅

**Comment by Stanzilla** [comment]
@bet4it they don't care about Hyper :D

**Comment by ppot** [comment]
Lord. Nice cleanup.

**Comment by bet4it** [comment]
Just find that 60883049c536348061d6dd51c59cb39fd8dffbaa could work on Linux. Linux will add the (old) icon to the notification automatically. The icon disappeared before because I run it by `npm run app`. 

You could remove the check for Linux for a cleaner code.

**Comment by LabhanshAgrawal** [comment]
@bet4it  After `yarn run dist` do you get new or old or both icons?

**Comment by bet4it** [comment]
I just realize it may be the effect of the global icon installed by package manager, so I uninstall hyper in package manager and use the AppImage built by Github actions.
60883049c536348061d6dd51c59cb39fd8dffbaa~ : no icon
60883049c536348061d6dd51c59cb39fd8dffbaa : no icon
dbed5bac9b4beb8ee208b23a5e5f2ab862c9a95e : new icon

When the hyper (packaged with old icon) is installed by package manager and use the AppImage, I get:
60883049c536348061d6dd51c59cb39fd8dffbaa~ : old icon
60883049c536348061d6dd51c59cb39fd8dffbaa : old icon
dbed5bac9b4beb8ee208b23a5e5f2ab862c9a95e : new icon

Now it's very clear. 60883049c536348061d6dd51c59cb39fd8dffbaa behave the same way as before, and dbed5bac9b4beb8ee208b23a5e5f2ab862c9a95e will always add the new icon in notification.
Both icons will never happen.

**Comment by LabhanshAgrawal** [comment]
Like you said https://github.com/zeit/hyper/commit/60883049c536348061d6dd51c59cb39fd8dffbaa doesn't have icon in the first scenario and https://github.com/zeit/hyper/commit/dbed5bac9b4beb8ee208b23a5e5f2ab862c9a95e always has the new icon, I think it's ok to leave it like that.

P.S. Both icons happen on macOS if icon in electron notification is enabled as the os also adds an icon.

**Pull request merged**
