### PR TITLE
update readme to warn that choco install gets an old version.

### PR DESCRIPTION
**Pull request by air**

### CODE REVIEW

**Comment by matheuss** [comment]
@air how could we update the version there?

**Comment by air** [comment]
Looks like the latest is in review, and the one before that never got published for a different reason https://chocolatey.org/packages/hyper#versionhistory

**Comment by rauchg** [comment]
For now I'll add the warn, would be great to automate the process for choco (somehow) so it's always up to date

**Comment by rauchg** [comment]
Thanks @air

**Comment by air** [comment]
👍

**Comment by chantisnake** [comment]
Hi, I am the maintainer of chocolatey package of hyper.

I have an update script at [chocolateyPackage](https://github.com/chantisnake/chocolateyPackage): https://github.com/chantisnake/chocolateyPackage/blob/master/UpdateScript.ps1

This script uses my powershell package: [github2choco](https://github.com/chantisnake/github2choco)

If you have someone good at powershell in your development team, I would love to assist you guys to create your automation script.

**Comment by chabou** [comment]
@chantisnake Thank you for you help. Can you open an issue: "Automatic choco update" with these informations?
It will be easier to find someone to achieve this

**Pull request merged**
