### PR TITLE
feat: add close tab button config (#720)

### PR DESCRIPTION
**Pull request by bildepunkt**

### CODE REVIEW

**Comment by knownasilya** [comment]
Not sure this is the best solution, see my comment https://github.com/zeit/hyperterm/issues/720#issuecomment-250276027

**Comment by rauchg** [comment]
Probably easier to just add a line of CSS?

**Comment by bildepunkt** [comment]
good call @rauchg! leave it to me to over-engineer...

**Comment by bildepunkt** [comment]
@rauchg 
now that I've looked at it, I'm not sure how to do this with css. I thought this would work:
``` 
// lib/components/tab.js
styles() {
  ...
    icon: {
      ...
      display: this.props.showCloseTabBtn
        ? 'inline-block'
        : 'none',
```
but styles are not parsed by webpack before they are bundled, and seeing how there are no css files, I can't simply write a css rule.

it seems like a small case for beefing up webpack's css handling, do you have any suggestions on where to start?
thanks

**Comment by knownasilya** [comment]
I think he means in your settings styles, not as a change to the project.

**Comment by bildepunkt** [comment]
Thank you @knownasilya, that makes sense.

**Comment by leo** [comment]
Do it via CSS; we won't introduce a config option for this. :blush:

**Comment by karlhorky** [comment]
Thanks for giving this a shot @bildepunkt.

**Comment by bildepunkt** [comment]
np :) it was fun

**Comment by karlhorky** [comment]
@leo I'm assuming until there's a solution for #14 I'll have to create a plugin for this?

**Comment by karlhorky** [comment]
Created a plugin for now: https://github.com/karlhorky/hyper-no-close

**Pull request closed without merging**
