### PR TITLE
Moved version from app/package.json to root

### LINKED ISSUE #2894: Move app version string from app/package.json to root package.json
Having version number in root `package.json` will permit to use the full power of https://github.com/zeit/release

### PR DESCRIPTION
**Pull request by Manish-Giri**
Moved `version` from `app/package.json` to root `package.json`. 

Tested with `yarn run dev` and `yarn run app`, although this change shouldn't break anything - 

hyp2

Fixes #2894

### CODE REVIEW

**Comment by Manish-Giri** [comment]
Oops, completely overlooked that `version` is mandatory in `package.json`. Should I leave the original version in `app/package.json` as is?

**Comment by timothyis** [comment]
@Manish-Giri I think it should be fine unless it causes any errors? The top-level package.json didn't have a version before, so it shouldn't matter that the other doesn't have a version now.

**Comment by chabou** [comment]
You should pay attention on 2 things:
* Code that requires this version like: https://github.com/zeit/hyper/blob/2de45245bf46484daef1efdd070f2a8b6329515a/app/notifications.js#L4
* Electron builder: when executing `yarn dist`

**Comment by timneutkens** [comment]
I'm going to close this since the PR is stale.

**Pull request closed without merging**
