### PR TITLE
[NO MERGE] Add rdp connection wait to troubleshoot build problems

### PR DESCRIPTION
**Pull request by vors**
This is troubleshooting PR to figure out why builds are failing on windows.
Follow-up from https://github.com/zeit/hyper/pull/984#issuecomment-260765659

### CODE REVIEW

**Comment by vors** [comment]
When I rdp to the machine, this is what I found

image

**Comment by vors** [comment]
There were 3 hyper windows open (I think it's during the test run).
Every one of them triggered this error.
That was the reason, why builds hanged.
Once I closed all of them, the build process continued.
Then it failed on packing (I think it's unrelated).
https://ci.appveyor.com/project/appveyor-zeit/hyper/build/1.0.101

**Comment by matheuss** [comment]
Thank you @vors! Check #988 – people are able to reproduce it. I'll look into it tomorrow 👍

**Comment by vors** [comment]
oh cool, it's indeed the same as #988
Just hard to see from the console, because pop-up doesn't show up in the logs.

**Pull request closed without merging**
