### PR TITLE
Reset bgColor

### PR DESCRIPTION
**Pull request by ppot**
Reset backgroundColor of window
Whitout update:
bgcolor_current

With update:
reset_bgcolor

### CODE REVIEW

**Comment by albinekb** [comment]
Add a comment as to why this is needed please 👌🙌

**Comment by ppot** [comment]
@albinekb I will make you a gif 📦

**Comment by rauchg** [comment]
A comment in the code is a great idea +1 @albinekb

**Comment by ppot** [comment]
@rauchg  Done 👍

**Pull request merged**
