### PR TITLE
Shrinkwrap all the deps to lock them down to known working versions

### PR DESCRIPTION
**Pull request by MrRio**
Updates can be handled with greenkeeper. Shrinkwrap will ensure that the exact working deps can be preserved in the history of the project. This makes it much easier to do git bisect to find regressions, and we can always have a cloneable and reproducable repo. 

Sometimes when a fuzzy version specification in packages.json matches a newer version of a dep, it can break things in unexpected ways. With shrinkwrapping, we can easily opt-in and manage those upgrades with the PRs from Greenkeeper instead.

### CODE REVIEW

**Comment by MrRio** [comment]
Build broken due to https://github.com/zeit/hyperterm/pull/533

**Comment by rauchg** [comment]
SGTM!

**Comment by MrRio** [comment]
@rauchg hah, you not a shrinkwrap fan?

**Comment by MrRio** [comment]
I guess you've got the non-dev deps pinned

**Comment by MrRio** [comment]
Greenkeeper doesn't actually support this, I thought it did, but they're working on it https://github.com/greenkeeperio/greenkeeper/issues/96

**Comment by ekmartin** [comment]
@MrRio: Should we close this and revisit when Greenkeeper release support for shrinkwrapping?

**Comment by leo** [comment]
@ekmartin Yes! 😊

**Pull request closed without merging**
