### PR TITLE
Add tray icon and set single instance mode to improve startup time on Windows

### PR DESCRIPTION
**Pull request by phungtuanhoang1996**
This is my attempt to address ther slow startup time on Windows, and also my first attempt to contribute to an open-source project (because I really like Hyper)

Please feel free to review and comment on what can be improve / went wrong. Thanks! 😄

Changed hyper to be running single instance mode on windows
Added a tray icon with exit option and new window option

Always Preloads a hidden window (without rpc handler and terminal session)
When a new window needs to be opened, the preloaded window will have its rpc and terminal session attached and brough to front

### CODE REVIEW

**Comment by chabou** [comment]
🙏 @phungtuanhoang1996 awesome work!

I will review this ASAP.
Thank you so much for your help.

My first thought was: is this a common behavior on Windows to not quit an app? Maybe we should add an opt-out option?
I remember that other apps (like Skype) offer a way to really quit the app (in context menu on tray icon, if I remember correctly).

**Comment by phungtuanhoang1996** [comment]
I did include an option to really quit the app in the context menu.
I can make an opt-out option as well.

**Comment by chabou** [comment]
Oh... I didn't see the systray context menu. Sorry.

For the option, let see if user are complaining about this.
This is the Hyper behavior on macOS and this is totally ok to me.

**Comment by chabou** [comment]
We are really honored to merge your first open-source contribution 🙏 
Thank you!

**Pull request merged**
