### PR TITLE
Display full download table on mobile

### PR DESCRIPTION
**Pull request by Angristan**
On mobile, the 64 bits column is hidden, which is kind of misleading since all the 32 bits cells are "coming soon", except macOS:

screenshot_24-01-2018_19-44-53

What it looks like with this PR:

screenshot_24-01-2018_19-44-42

### CODE REVIEW

**Comment by albinekb** [comment]
Great with the screenshots 👌

**Comment by albinekb** [comment]
I think we can remove the 32 bit column all together. @chabou @leo @timothy?

**Comment by Angristan** [comment]
That was fast haha. You're welcome 👍

**Comment by leo** [comment]
👍

**Comment by albinekb** [comment]
@Angristan do you mind removing the 32-bit column all together in this PR? Or do it in another one 🙏

**Comment by Angristan** [comment]
Oops, sorry, I didn't check my commit and something went wrong. I'll open another PR!

**Comment by albinekb** [comment]
No problem! @Angristan I'll check it out when it arrives 👍

**Pull request closed without merging**
