### PR TITLE
fixed issue with dual-gpus getting disabled

### PR DESCRIPTION
**Pull request by ethanx94**
#2607

### CODE REVIEW

**Comment by albinekb** [comment]
If I understand this correctly, this flag will tell macOS that the app supports switching between GPUs? (iGPU & discrete card / eGPU) whereas without this flag, it will force the better GPU to be on all the time? 🤔 

What are the drawbacks of adding this flag? Are there issues with GPU switching and electron/chrome? If not, why isn't this default?

Sorry for all the questions but I want to make sure this doesn't negatively effect other users 👍 @ethanx94

**Comment by ethanx94** [comment]
Drawbacks I can think of: None except I believe this is considered an experimental flag. I think that’s why it isn’t default. I haven’t throughly tested this on other platforms however.

Furthermore this doesn’t seem to be supported for me in newer versions of Chrome/Chromium. Meaning it doesn’t hurt anything, but just doesn’t do anything different. If Electron is ever updated to use a newer version of Chromium this argument may become useless again.

This has a lot to due with how Chrome is forcing graphics switching as soon as Hyper/VSCode/Any Electron app is opened. See my comments on this here: https://github.com/zeit/hyper/issues/2607#issuecomment-358201484

A more thorough look at what is going on would be to go to chrome://gpu with this flag on and look at the GL_RENDERER. I’m not sure how to get to here from the Electron app.
Someone with a deeper understanding of Chrome might be able to shed some light on this but all I can say with confidence is that I had an issue and this flag fixed it.

**Comment by albinekb** [comment]
Thanks for that @ethanx94 👍 Yes, chrome and electron is a bit messy. I'm not sure what to do. @chabou thoughts on this one?

Maybe we should put this in a plugin and link people that want this fix to activate the plugin? It feels to risky to change it for everyone when we only ever got 1 report of this being an issue. 

VS Code, Slack and all the other Electron apps would also need to add this flag for it to be effective, since in most cases Hyper isn't the only electron app running on the system.

Thoughts? 🌡

**Comment by saamalik** [comment]
The 'gfxCardStatus' app indicates which apps are using iGPU vs eGPU. Anyway, from my _limited_ testing, _Hyper_ continues to run in 'Integrated' GPU _even_ with this PR. Is there some special command needed to kick in the dedicated graphics card?

My computer: MacBook Pro 15in mid-2017.

**Pull request closed without merging**
