### PR TITLE
🙌 unicode/emoji fix 

### PR DESCRIPTION
**Pull request by dotcypress**
Emoji fix.

Related PR: https://github.com/zeit/hyper/pull/740

Before:
screen shot 2016-11-19 at 2 47 39 am

After:
screen shot 2016-11-19 at 2 48 27 am

### CODE REVIEW

**Comment by matheuss** [comment]
Amazing, @dotcypress 😌 

We still need to fix the insertion, removal, and the behavior of more complex emojis:

kapture 2016-11-19 at 10 15 43

cc @rauchg @rginda

**Comment by rauchg** [comment]
@dotcypress this is amazing stuff

**Comment by matheuss** [comment]
So, @dotcypress: I think the last thing we should do before merging is finding a way to add `line-height: 1em` to `<x-row>` if there's any emoji on the screen.
This is not the best solution in the world, but I think it's enough until we manage to fix `line-height` on `hterm` 👌

**Comment by matheuss** [comment]
Ping @dotcypress @rauchg: should we merge as it is?

**Comment by rauchg** [comment]
Yes. I'd love to fix the other issue (maybe @dotcypress has good ideas), but for now this is an improvement

**Pull request merged**
