### PR TITLE
Add Spanish keyboard compatibility #584

### PR DESCRIPTION
**Pull request by pablopunk**
The problem with the character `~` was not fixed for Spanish keyboards, which is `Alt+Ñ`.

### CODE REVIEW

**Comment by ekmartin** [comment]
Hi! Would you mind trying out https://github.com/zeit/hyperterm/pull/214 and see if that resolves your issue?

**Comment by pablopunk** [comment]
Nope, the `~` is not working there either. But I also noticed that on master I can't write this character "`" but in that branch is solved.

**Comment by pablopunk** [comment]
Is it ready to merge then?

**btw I know some Spanish users that don't use this app JUST because os this error :P **

**Comment by matheuss** [comment]
Whoa, no clue why this wasn't merged before. I'm sorry @pablopunk 😩 
Closing in favor of #1006 🙌

**Comment by pablopunk** [comment]
@matheuss Ok, I cloned it and it seems to fix it. Thanks.

**Comment by matheuss** [comment]
Good to know! It'll be shipped *very soon* 😄

**Pull request closed without merging**
