### PR TITLE
Typo fix: "wihtout" => "without"

### PR DESCRIPTION
**Pull request by Flaque**
# Changes made
* Really simple typo fix I stumbled across

### CODE REVIEW

**Comment by Flaque** [comment]
hurray

**Comment by chabou** [comment]
Thank you :pray:

**Comment by albinekb** [comment]
haha @Flaque I had this one https://soundcloud.com/lisaavecuns/cheryl-lynn-got-to-be-real-dj-s-bootleg-dance-re-mix in my ears when i opened this PR 😂

**Comment by Flaque** [comment]
@albinekb Welp, now I know what I'm listening to on repeat for the rest of the day.

**Pull request merged**
