### PR TITLE
Bump electron from 1.8.4 to 1.8.7

### PR DESCRIPTION
**Pull request by PlanetVaster**
Update electron to 1.8.7 from 1.8.4. Also of note we should look into upgrading to electron 2. This PR should be ready to merge, 1.8.7 is just bug fixes as well as a security patch.

### CODE REVIEW

**Comment by Stanzilla** [comment]
You forgot to update the lockfile, and yeah we want to, electron 2 PR is here https://github.com/zeit/hyper/pull/2967 just no one taking care of business since @chabou is busy atm :)

**Comment by PlanetVaster** [comment]
I have updated the lock file (I believe I did this correctly, I've never used yarn so let me know if I did it wrong).

**Comment by PlanetVaster** [comment]
Can someone review this? Maybe @Stanzilla

**Comment by chabou** [comment]
Be careful v1.8.7 (and below certainly) has a critical security issue: https://electronjs.org/blog/web-preferences-fix

I will certainly merge this PR and right after, upgrade `electron` to v1.8.8

**Comment by chabou** [comment]
Thank you so much for your help @PlanetVaster 🙏

**Pull request merged**
