### PR TITLE
[Windows] Add right click copy/paste

### LINKED ISSUE #1019: Right click to copy and paste
Hi, that's what we can do on powershell, it's be nice if we can do that too on hyper, and another one, can you please add a shortcut for copy and paste: like Ctrl+Shift+C/V. 

Thank you

### PR DESCRIPTION
**Pull request by Specro**
Adds the usual Windows behavior of copying or pasting when right clicking in the terminal. Would be nice if more people would test that this works correctly 😄 Besides that it's ready to be merged.

Closes #1019

### CODE REVIEW

**Comment by kleinfreund** [comment]
Would this lead to copying with rightclick on Windows by default?

That said, is there a main issue regarding cross-platform default keybindings? The various ways different operating system and terminal programs use shortcuts is an incredible mess. Copying via <kbd>Mouse 2</kbd> (rightclick)? Or even <kbd>Shift</kbd><kbd>Ins</kbd>? Or <kbd>Ctrl</kbd><kbd>Shift</kbd><kbd>C</kbd>? Or only <kbd>Ctrl</kbd><kbd>C</kbd>? I'm sure there are even more ways.

In general, should the Hyper keybindings match the OS default? In this case, at this point I would argue that the default on Windows is <kbd>Ctrl</kbd><kbd>C</kbd>.

**Comment by albinekb** [comment]
I would like this an an option. It's weird for users if Hyper acts different on based on OS...

**Comment by Specro** [comment]
@kleinfreund It seems Windows cmd has a QuickEdit mode which if enabled, lets the user select text in the window and copy/paste it on right click. Without it enabled on right click a context menu is shown and then cmd actually considers <kbd>Enter</kbd> the default key for copying. 

So one more key to that mess you mentioned 😕

I think we should go with @albinekb idea of making an option for this.

**Comment by ppot** [comment]
Appart form this. This type of action should be handled by hterm directly in the onMouseDown_

**Comment by paulcbetts** [comment]
> Would this lead to copying with rightclick on Windows by default?

If there is a selection, right-click == Copy, if not, right-click == Paste

> In general, should the Hyper keybindings match the OS default? In this case, at this point I would argue that the default on Windows is CtrlC.

Not in a terminal, because of the obvious conflict between Ctrl-C as SIGINT. The old-school DOS shortcut Shift-Insert applies here.

QuickEdit is a deeply Windows Thing but should indeed be an option in Hyper if it wants to be a terminal on Windows (tbh, if you got used to it on macOS or Linux, I bet you'd get value out of it there too tho). I suspect it should be opt-in though.

> Also you paste on right-click, what if you want to use the context-menu? 🤔

When QuickEdit is enabled, there is no context-menu

**Comment by Specro** [comment]
@paulcbetts Very well explained 👌 
@ppot Is this ok? 🤔 

I named the config option quick edit for now. If anyone has any better suggestions they're welcome to share 😄

**Comment by paulcbetts** [comment]
> I would like this to be an opt-in-option. It's weird for users if Hyper acts different on based on OS...

I think that this should be enabled by default on Windows, since it is also enabled by default in the default terminal on Win10

**Comment by matheuss** [comment]
Thanks @Specro 🙌

**Pull request merged**
