### PR TITLE
Add scrollback option to config

### PR DESCRIPTION
**Pull request by jaridmargolin**
As I was preparing this PR I was surprised to find that there was very little test coverage. Perhaps I am missing something?

It'd be great to get this pushed through and I am fairly confident the change is working as expected, but it feels strange to add functionality without writing/running tests 🤔

... Additionally, if there is interest in merging this PR, documentation should be updated accordingly.

### CODE REVIEW

**Comment by chabou** [comment]
@jaridmargolin Thank you for this PR 🙏 

You're totally right. We need more unit tests and more functional tests with `spectron`

**Comment by jcrben** [comment]
Never too late to start. At least xterm is decently tested (see e.g. https://github.com/xtermjs/xterm.js/tree/master/src)... looking into tests. At work I'm spoiled by TDD using jest and jsdom with mocking of the API data (which is tested separately) - would like to be able to have a similar TDD flow.

**Comment by AhmedBM** [comment]
I just added the scollback option in v2.1.1 and im not seeing it. It looks like this change was merged sometime ago so it should be there. Am i missing something here?

**Comment by sankalp-khare** [comment]
@AhmedBM I can confirm it works in 2.1.2, though I don't know how to set it to infinite. For now I went with an absurdly large value
```
        scrollback: 2147483647,
```

**Comment by aecorredor** [comment]
> @AhmedBM I can confirm it works in 2.1.2, though I don't know how to set it to infinite. For now I went with an absurdly large value
> 
> ```
>         scrollback: 2147483647,
> ```

I tried this and don't really get that much more when scrolling back up. It's for sure not close to being infinite. Any ideas?

**Comment by rjurney** [comment]
I still don't have additional scrollback after setting:

```json
{
    scrollback: 100000000
}
```

What do I do?

**Comment by ddimico** [comment]
Agree with @rjurney, scrollback appears to not actually do anything to the buffer length. Seems a bit crazy this isn't something of higher priority. I have no idea how people are using this with only an 1000 buffer length.

**Comment by rjurney** [comment]
@ddimico This makes the thing unusable. I abandoned it. If it is fixed I'll look again.

**Comment by jcruzdzk** [comment]
where i set this value? in .hyper.js?

**Comment by jerch** [comment]
hyper prolly solely relies on the scrollback handling done by xterm.js and has no additional infinite scroll shim. If so, you should not try to set it to some arbitrary high value or the app will crash with OOM.

Some calculations - JS engines typically dont allow more than ~2GB to be claimed. A cell takes 12 bytes, thus:
- at 100 cells per line: max of ~1.5M lines
- at 1000 cells per line: max of ~150k lines

and so on...

**Comment by ajilling** [comment]
Echoing this does not work - using config.json

**Comment by aecorredor** [comment]
Just wanted to touch base on this. Did somebody ever find a way to get this working? It still doesn't work for me even on the latest hyper version.

**Comment by dubbatk** [comment]
> Just wanted to touch base on this. Did somebody ever find a way to get this working? It still doesn't work for me even on the latest hyper version.

I would like to confirm that this works. You will need to add the setting under config: {...}, it is the same as adding lineHeight or letterSpacing. Follow the same format as any general setting under the config block :-)

**Comment by PButcher** [comment]
The `scrollback` option should be added to the `~/.hyper.js` by default. The default limit is irritatingly small.

**Comment by PButcher** [comment]
The `scrollback` option should be added to `~/.hyper.js` by default. The default limit is irritatingly small.

The option does work, you just have to add it yourself.

**Pull request merged**
