### PR TITLE
fix: Hyper window freezes when I try to close it

### PR DESCRIPTION
**Pull request by ivanwonder**
I found the windows freezes because of node-pty can not be killed, and the new version [0.8.1](https://github.com/microsoft/node-pty/releases/tag/0.8.1) of node-pty fix it. and I also add a config `useConpty`. the related issues #3736.
another related issues #3758 happened because of the warmed-up session exit(I don't know why). If set config `useConpty` to false, it will open correctly according to the test on my windows 10  version 1903.

### CODE REVIEW

**Comment by chabou** [comment]
Thank you for your help @ivanwonder on these issues!

Multiple things are mixed in this PR. And I want to be sure that they are related.

Upgrading `node-pty` is a really good catch. Isn't it enough to fix #3736 ? Or do we need your additions about `initialSession` too?

Why do you need `useConpty` config? Can you explain the issue your encountered without it?

**Comment by ivanwonder** [comment]
I cannot say it is enough to fix #3736.
According to the error info of #3736. the problem is the code fire event of `session exit` without `uid`.
https://github.com/zeit/hyper/blob/758e93c21e98556dd50acd81e8dc27615eebe787/lib/index.js#L61
https://github.com/zeit/hyper/blob/758e93c21e98556dd50acd81e8dc27615eebe787/app/ui/window.js#L130
https://github.com/zeit/hyper/blob/758e93c21e98556dd50acd81e8dc27615eebe787/app/ui/window.js#L136
so my thought of the additions about `initialSession` is clean it and creates a new one.
https://github.com/zeit/hyper/blob/758e93c21e98556dd50acd81e8dc27615eebe787/app/ui/window.js#L146
but the new one still exit. **so the main problem is why session exit when open hyper with the hyper cli.**
I discovered that if set the `useConpty` to false, the issues #3736 solved. But I still cannot explain the main problem why session exit and find info about it until now. and the vscode have the setting `Windows Enable Conpty`.

**Comment by ThraaxSession** [comment]
I think many other windows user think is annoying. Do you think it's worth for a new release? I caught this error too.

**Comment by Stanzilla** [comment]
It is, yeah. But we don't have anyone doing releases currently.

**Pull request merged**
