### PR TITLE
Add snapcraft build

### PR DESCRIPTION
**Pull request by pablopunk**
Not sure why this was removed at some point but I got it working on my pc. The only thing left is to upload the snap to snapcraft (https://docs.snapcraft.io/build-snaps/electron) and set up the github integration for automatic builds and updates (https://snapcraft.io/build)

This is related to https://github.com/zeit/hyper/issues/1229

### CODE REVIEW

**Comment by albinekb** [comment]
How do I go about testing this? @pablopunk just running the build and it should build the snap too? What platforms can it be built on? Ubuntu only?

**Comment by pablopunk** [comment]
@albinekb 

Yep, `npm run dist` should get you a snap inside `dist/` folder. And then install it with `sudo snap install ./dist/...`. Of course you need `snapd` to do that.

The good thing about snapcraft.io is that the packages are universal, so they work across distros. I did try it only in Ubuntu but it should work okay in others...

**Comment by pablopunk** [comment]
@chabou hey! Thanks for the merge. One more thing, when are we getting the snap uploaded to [snapcraft.io](https://snapcraft.io/)? Someone should link this repo to snap (see https://snapcraft.io/build)

**Comment by chabou** [comment]
I (or any helper) will upload the snap after next stable release

**Pull request merged**
