### PR TITLE
upgrading hterm-umdjs to 1.1.4

### PR DESCRIPTION
**Pull request by MartyGentillon**
Includes various hterm bug fixes including one where under certain
zooms and fonts the last line of console output does not display.

Updated hterm from version 15ed49071379e51ae47d929134366eb156a6943a
to a65fd913db6e931756d1199641aa45c556336dd4

see https://chromium.googlesource.com/apps/libapps/+log/HEAD/hterm
see https://chromium.googlesource.com/apps/libapps/+/6cec52ab8e442a4ec35c16907187f4e1a21a286f

### CODE REVIEW

**Comment by MartyGentillon** [comment]
I have run this and can confirm that the last line of shell output appears to display correctly, even after prolonged output.

**Comment by chabou** [comment]
I think that this fix could be useful: https://chromium.googlesource.com/apps/libapps/+/ccbc9ba0f0015da2b545dfb1751496eeeb92a5f6

To be precise, `hterm-umdjs` v1.1.4 updates `hterm` to a65fd913db6e931756d1199641aa45c556336dd4 (517c3ec8d8a52c3a166222b017ce16551be17134 is excluded)

Warning: some hterm next commits (but not included in this PR) could be harmful: https://chromium.googlesource.com/apps/libapps/+/70b94693f7c43e7a9a668479e5633f0d1770ac2e

**Comment by MartyGentillon** [comment]
ccbc9ba0f0015da2b545dfb1751496eeeb92a5f6 is a bug fix for a bug that was introduced earlier in the set of changes (7354202ec171287e200ec075c40e34784005fa97).  Basically, it was introduced and then fixed between the two versions, and so shouldn't have any effect on hyper's behavior.

I suppose that I could update the commit message.

**Comment by chabou** [comment]
Oh, you're right for ccbc9ba0f0015da2b545dfb1751496eeeb92a5f6 !

**Comment by MartyGentillon** [comment]
Commit message updated to be correct.

**Comment by MartyGentillon** [comment]
Done.

**Comment by chabou** [comment]
the only other commit is 65f33d65b66b06ba00ce5e92154695de5566ec17 but:
> addBindings continues to work the way it did before

I tried this PR locally and everything seems ok

**Comment by CodeTheory** [comment]
Thanks @MartyGentillon <3

**Pull request merged**
