### PR TITLE
Improve Hyper 3 Canary and Stable icons

### PR DESCRIPTION
**Pull request by evilrabbit**
screen shot 2019-02-09 at 10 21 35 am

New Icons:
screen shot 2019-02-09 at 10 23 48 am

### CODE REVIEW

**Comment by MAPESO** [comment]
@chabou  @juancampa Hi, canary icon will be displayed in `macOS Mojave`? I remember when it came out hyper 2 there were also canary icons but they were not shown 😿 

I guess the icon will show depending on what we have in `updateChannel: 'xxxxx'`

**Comment by c-bandy** [comment]
The canary icon does not seem to display for me on macOS Mojave, even after restarting the app.

**Comment by chabou** [comment]
I think you have to reinstall canary version (from GitHub release page). SelfUpdate doesn't update app icon imo.

**Comment by c-bandy** [comment]
@chabou When the icon was updated a few days ago it changed without me doing anything in particular. I think this is specific to the canary logo changing.

**Comment by J12ATA** [comment]
How would I access the gold icon? Is this done via editing my ~/.hyper.js configuration file? I am running the Hyper 3 'canary' version.

**Comment by rfgamaral** [comment]
These new icons don't look that great on Windows taskbar:

image

**Pull request merged**
