### PR TITLE
Transparency support on Linux

### PR DESCRIPTION
**Pull request by stepanvanzuriak**
Using @rewhex comment https://github.com/electron/electron/issues/2170#issuecomment-355144344

2018-01-09-124311_1920x1080_scrot

**Tested on**: Manjaro 17.1.1 Hakoila 

**With hyper.js**: 
```
// Future versions of Hyper may add additional config options,
// which will not automatically be merged into this file.
// See https://hyper.is#cfg for all currently supported options.

module.exports = {
  config: {
    // Choose either "stable" for receiving highly polished,
    // or "canary" for less polished but more frequent updates
    updateChannel: 'canary',

    // default font size in pixels for all tabs
    fontSize: 14,

    // font family with optional fallbacks
    fontFamily: 'Menlo, "DejaVu Sans Mono", Consolas, "Lucida Console", monospace',

    // terminal cursor background color and opacity (hex, rgb, hsl, hsv, hwb or cmyk)
    cursorColor: 'white',

    // `BEAM` for |, `UNDERLINE` for _, `BLOCK` for █
    cursorShape: 'BLOCK',

    // set to true for blinking cursor
    cursorBlink: false,

    // color of the text
    foregroundColor: '',

    // terminal background color
    backgroundColor: 'rgba(0, 0, 0, 0.5)',

    // border color (window, tabs)
    borderColor: '',

    // custom css to embed in the main window
    css: '',

    // custom css to embed in the terminal window
    termCSS: '',

    // set to `true` (without backticks and without quotes) if you're using a
    // Linux setup that doesn't show native menus
    // default: `false` on Linux, `true` on Windows (ignored on macOS)
    showHamburgerMenu: '',

    // set to `false` if you want to hide the minimize, maximize and close buttons
    // additionally, set to `'left'` if you want them on the left, like in Ubuntu
    // default: `true` on windows and Linux (ignored on macOS)
    showWindowControls: 'yes',

    // custom padding (css format, i.e.: `top right bottom left`)
    padding: '12px 14px',

    // the full list. if you're going to provide the full color palette,
    // including the 6 x 6 color cubes and the grayscale map, just provide
    // an array here instead of a color map object
     colors: {
      black: '#000000',
      red: '#ff0000',
      green: '#33ff00',
      yellow: '#ffff00',
      blue: '#0066ff',
      magenta: '#cc00ff',
      cyan: '#00ffff',
      white: '#d0d0d0',
      lightBlack: '#808080',
      lightRed: '#ff0000',
      lightGreen: '#33ff00',
      lightYellow: '#ffff00',
      lightBlue: '#0066ff',
      lightMagenta: '#cc00ff',
      lightCyan: '#00ffff',
      lightWhite: '#ffffff'
    },

    // the shell to run when spawning a new session (i.e. /usr/local/bin/fish)
    // if left empty, your system's login shell will be used by default
    //
    // Windows
    // - Make sure to use a full path if the binary name doesn't work
    // - Remove `--login` in shellArgs
    //
    // Bash on Windows
    // - Example: `C:\\Windows\\System32\\bash.exe`
    //
    // Powershell on Windows
    // - Example: `C:\\WINDOWS\\System32\\WindowsPowerShell\\v1.0\\powershell.exe`
    shell: '',

    // for setting shell arguments (i.e. for using interactive shellArgs: ['-i'])
    // by default ['--login'] will be used
    shellArgs: ['--login'],

    // for environment variables
    env: {},

    // set to false for no bell
    bell: 'SOUND',

    // if true, selected text will automatically be copied to the clipboard
    copyOnSelect: false,

    // if true, on right click selected text will be copied or pasted if no
    // selection is present (true by default on Windows)
    // quickEdit: true,

    // URL to custom bell
    // bellSoundURL: 'http://example.com/bell.mp3',

    // for advanced config flags please refer to https://hyper.is/#cfg
    // materialSyntax: 'dark'
  },

  // a list of plugins to fetch and install from npm
  // format: [@org/]project[#version]
  // examples:
  //   `hyperpower`
  //   `@company/project`
  //   `project#1.0.1`
  plugins: [],

  // in development, you can create a directory under
  // `~/.hyper_plugins/local/` and include it here
  // to load it and avoid it being `npm install`ed
  localPlugins: [],

  keymaps: {
    // Example
  },
};
```

### CODE REVIEW

**Comment by chabou** [comment]
Thank you for your help.

Please read other comments in electron issue.
`unregisterProtocol` seems not necessary, it works only because it adds some delay.
If it works wthout `app.disableHardwareAcceleration()` as suggested in Electron issue, you should add a comment there.

**Comment by stepanvanzuriak** [comment]
Add comment in issue, hope this helps in some way

**Comment by albinekb** [comment]
I think this should be opt-in (via a config setting) so that you can chose to take the performance hit if you want to trade it for transparency, I would not.

**Comment by stepanvanzuriak** [comment]
If we do not get answer from electron developers maybe it may be wise to use  `setTimeout` hack?

**Comment by lucasqueiroz** [comment]
Thank you! It's something that really bothers me... I hope someday it can be as beautiful as it is on macOS again

**Comment by lucasqueiroz** [comment]
I just tested it with Ubuntu 17.10 and apparently it's not working :/ It just gives me a black background (with your config file).

**Comment by jonaustin** [comment]
This is working great on Arch Linux (Manjaro). Thanks!

**Comment by justUmen** [comment]
@stepanvanzuriak Amazing work, thanks ! I can maybe drop all my horrendous hacks.
But were you able to achieve 100% transparency ?
If i try below 10%, background turn white : `backgroundColor: 'rgba(0, 0, 0, 0)',`

**Comment by stepanvanzuriak** [comment]
@justUmen I don't test it

**Comment by stepanvanzuriak** [comment]
Update with https://github.com/electron/electron/issues/2170#issuecomment-361549395

**Comment by Stanzilla** [comment]
Hey there, @stepanvanzuriak!

This needs a rebase, are you willing to pick this up again?

**Comment by stepanvanzuriak** [comment]
Hi @Stanzilla 

What should I do? (I don't know how to do rebase in github 😥)

**Comment by Stanzilla** [comment]
No worries, https://github.com/edx/edx-platform/wiki/How-to-Rebase-a-Pull-Request is actually a good guide.

**Comment by stepanvanzuriak** [comment]
@Stanzilla I hope I do this right 🙏

**Comment by albinekb** [comment]
Looks like you did everything correctly, however you accidentially added `yarn-error.log`, we have added this to .gitignore now as per #2928, you need to remove this file as we don't want it in the codebase 👍 🙏

**Comment by stepanvanzuriak** [comment]
@albinekb Ready

**Comment by stepanvanzuriak** [comment]
@jeffarese We must wait https://github.com/electron/electron/issues/2170 (Yes i'ts closed, but community still update different hacks how implement transparency)

**Comment by stepanvanzuriak** [comment]
🎉 Right now bug is confirmed by Choromium developers [Bug issue page](https://bugs.chromium.org/p/chromium/issues/detail?id=854601#c7)

**Comment by from-nibly** [comment]
any news on this? Transparency is the only thing keeping me from using hyper

**Comment by stepanvanzuriak** [comment]
@from-nibly As I said earlier  

> bug is confirmed by Choromium developers Bug issue page

**Comment by talentlessguy** [comment]
Any progress on this PR?

**Comment by Stanzilla** [comment]
not really, no.

**Comment by talentlessguy** [comment]
@Stanzilla so transparency won't work on Linux in general or just no progress on PR?

**Comment by Stanzilla** [comment]
on the PR

**Comment by stepanvanzuriak** [comment]
> @Stanzilla so transparency won't work on Linux in general or just no progress on PR?

As far as I know, Electron still has a leak of transparent support for Linux. Please see: https://github.com/electron/electron/issues/16809, https://bugs.chromium.org/p/chromium/issues/detail?id=854601#c7

**Comment by guy-kdm** [comment]
Are we still waiting for chromium?

**Comment by Stanzilla** [comment]
I don't think anyone is working on the PR either.

**Comment by stepanvanzuriak** [comment]
Maybe we can add some "experimental linux transparency flag" for now (with this hack) ?

**Pull request closed without merging**
