### PR TITLE
Add activity glow on tab title

### PR DESCRIPTION
**Pull request by chabou**
Each time that a tab have new activity, a glow effect is played:
hyper-activity_glow

Glow effect is throttled to 1 per second max

### CODE REVIEW

**Comment by chabou** [comment]
Fixes #536

**Comment by chabou** [comment]
here a new try with smaller and slower glow animation: 
hyper-activity_glow

**Comment by chabou** [comment]
thank you for your feedback @CodeTheory

**Comment by rauchg** [comment]
One way to do a less-obtrusive glow might be to just animate `opacity`. Bring it down to 0.8, then quickly back up to 1.

**Comment by chabou** [comment]
Here is glow effect with opacity:

hyper-activity_glow

**Comment by Stanzilla** [comment]
I personally think the glow looks better and is "more hyper" but the opacity version is fine as well.

**Comment by albinekb** [comment]
Maybe use the "facebook shimmer" effect? https://codepen.io/redouglas/pen/gobsm 🙉

**Comment by jbergstroem** [comment]
Talk about distracting 😢 -- ever run a big rsync in another tab? That tab would be blinking constantly. I would prefer if this wasn't default, but easily themeable -- its just too opinionated.

**Comment by chabou** [comment]
@timothyis What should we do?

**Comment by Stanzilla** [comment]
Should be an option, imo.

**Pull request closed without merging**
