### PR TITLE
re-implement `clear`, make it not buggy, fix CMD+K

### PR DESCRIPTION
**Pull request by rauchg**
This makes everything better

### CODE REVIEW

**Comment by ppot** [comment]
Sure?

**Comment by albinekb** [comment]
😂  awesome

**Comment by dcalhoun** [comment]
@rauchg were there specific issues/bugs that this resolved? I'm curious as to what this changed. Thanks.

**Comment by dcalhoun** [comment]
@rauchg to follow up on my previous comment, I ask specifically because I still see a lot of issues with clear in regards to using [Jest](https://facebook.github.io/jest/). When using Jest's `--watch` mode, the runner always produces odd output (e.g. the history of previous runs is accessible if you scroll upwards).

**Pull request merged**
