### PR TITLE
Fix copy/paste in vim/tmux

### LINKED ISSUE #773: Copy/paste broken in Vim/Tmux + Text selection broken in tmux
Clicking and dragging on text in tmux, such as a directory listing, does nothing.

Copy & paste also does nothing in tmux. I can paste all day long in a non-tmux pane but never in a tmux pane.

This is a show-stopper for me :sob: 

_I'm on Ubuntu 14.04_

### PR DESCRIPTION
**Pull request by flybayer**
This partially reverts commit a4315042fa3266d42b67e74f9ac3403ab7e3ca16.

Fixes #773, #789

/cc @ekmartin

### CODE REVIEW

**Comment by rauchg** [comment]
My question is: `-webkit-user-select` is producing this side effect, or was my logic for deciding when to make text unselectable wrong?

**Comment by flybayer** [comment]
@rauchg, I think it's the WebKit prefix. Moreover, it breaks pasting, not just text selection, which I don't understand 🤔 I'm limited on the debugging I can do on my daily Linux machine because my dev tools are broken.

**Comment by rauchg** [comment]
The problem is that I took out the `preventDefault` that made us lose focus when performing terminal clicks, but in the process I lost the functionality of making text unselectable when doing so. This was an attempt to restore that. I was unaware of these side effects :|

**Comment by rauchg** [comment]
I do agree with you that if we don't figure out something really soon, I'm down for sacrificing the text selection quirk when clicking and restoring copying and pasting :D

**Comment by pascalw** [comment]
I can confirm that this indeed fixes both being able to paste in vim as well as mouse support in tmux.

**Comment by dpo** [comment]
Any chance that this will be merged soon and included in a release?

**Comment by leo** [comment]
Please resolve the conflicts! Will merge it 😊

**Comment by leo** [comment]
Done in https://github.com/zeit/hyper/commit/f96d02480df9f8fd6116805b68ba1afbead459e9

**Pull request closed without merging**
