### PR TITLE
Makes fullscreen prettier on macOS (fixes #5 sorta)

### LINKED ISSUE #5: Make fullscreen look pretty (Title bar is transparent and overlaps content on fullscreen)
Currently, the title bar looks like this:

screen shot 2016-07-02 at 11 17 53

### PR DESCRIPTION
**Pull request by zacharyrs**
Adds a class to the main hyper element in fullscreen, and also removes the border shim + margin in the tabs. Also reverts transparent bar on macOS, giving a nicer menu in fullscreen.

Think it's all ready to merge. Runs fine in development, as well as when built for distribution.

PS: This is my first time even looking at react, so I'm not 100% sure if my code styling is on point, but I tried to mimic how the rest of the repo was written.

This PR sh

### CODE REVIEW

**Comment by albinekb** [comment]
Nice @zacharyrs, Can you provide brefore/after screenshots? Thanks 🙌

**Comment by zacharyrs** [comment]
Before entering fullscreen.
screen shot 2017-10-09 at 11 00 57 am

After entering fullscreen.
screen shot 2017-10-09 at 11 02 31 am

And when the menu is shown.
screen shot 2017-10-09 at 11 02 46 am

**Comment by zacharyrs** [comment]
Just thought I'd say, I haven't tested this on any other OS, but I was pretty careful not to break them either.

**Comment by zacharyrs** [comment]
@albinekb Just wondering what's happening?

**Comment by zacharyrs** [comment]
@Stanzilla sure thing, though it'll be a little bit!

**Comment by zacharyrs** [comment]
Unfortunately I've orphaned this PR, so take a look at #3014

**Pull request closed without merging**
