### PR TITLE
Update electron to v1.7.10 and other dependencies

### PR DESCRIPTION
**Pull request by Stanzilla**
Changelog: https://github.com/electron/electron/releases/tag/v1.7.10

### CODE REVIEW

**Comment by MindTooth** [comment]
Just leaving this here for the project managers.

https://dependabot.com

**Comment by chabou** [comment]
@MindTooth Do you know differences with https://github.com/apps/greenkeeper? And which is best to use?

**Comment by MindTooth** [comment]
I can't say.  Thought a project like Hyper.js — which uses a lot of node packages, would benefit from such a solution.  Greenkeeper seemed cool as well.

To quote their site:
>Greenkeeper is officially recommended by npm!

My apologies if I seemed competent in the field.

**Comment by Stanzilla** [comment]
build failure is fluke

**Comment by chabou** [comment]
Thank you @Stanzilla

**Pull request merged**
