### PR TITLE
Added pressed state to window buttons on windows / linux

### PR DESCRIPTION
**Pull request by levrik**
Not really visible on minimize, maximize and close buttons but on the menu button.

### CODE REVIEW

**Comment by ppot** [comment]
Need picture

**Comment by levrik** [comment]
@ppot Added.

**Comment by ppot** [comment]
Why the preset state on the `X` is red ?

**Comment by rauchg** [comment]
Ping @levrik

**Comment by levrik** [comment]
@rauchg @ppot Ah sorry. I did not change the `X` to being red. That was done before my PR.

**Comment by matheuss** [comment]
Yeah, the close button is read as per the design. CC @CodeTheory please review 😄

**Comment by CodeTheory** [comment]
The close button has a red hover to convey that the close button is something to take attention towards. As has most close buttons on most systems. Since I was trying to design the window controls to be an average of systems that use those window control positions and icons, I found that windows has just the close button holding a coloured hover. ¯\_(ツ)_/¯ consistency.

As for the PR, looks good to me!

**Pull request merged**
