### PR TITLE
Fix keyboard shortcuts on Linux and Windows

### LINKED ISSUE #274: Ctrl-based shortcuts don't work on Linux
In the menus, most shortcuts are listed using the `ctrl` key as the only modifier (likely an automatic artifact from macOS's `cmd`). Some examples:
- Copy `ctrl+c`
- Paste `ctrl+v`
- Close tab `ctrl+w`
- New tab `ctrl+t`

These shortcuts don't work, nor should they since they are essential shortcuts used within the shell. Copy and paste seem to work with the usual `ctrl+shift+c/v`, but I couldn't find working versions of any others in my few minutes of guessing.

### LINKED ISSUE #1025: [Windows] ctrl+T / ctrl+n / ctrl+w not working
- [x] I am on the [latest](https://github.com/zeit/hyper/releases/latest) Hyper.app version
- [x] I have searched the [issues](https://github.com/zeit/hyper/issues) of this repo and believe that this is not a duplicate

- **OS version and name**:  Windows 10
- **Hyper.app version**: 1.0.0 from appveyor

## Issue
ctrl+T / ctrl+n / ctrl+w shorcuts are not working. Instead, it's adding `^T`, `^N` and `^W` to my command input

### PR DESCRIPTION
**Pull request by matheuss**
This PR introduces a temporary fix for the issue with keyboard shortcuts (accelerators) on Windows and Linux.

The fix consists of a check on every `keyDown` event: if such event is a Hyper accelerator (`Ctrl+tab`, for example), we prevent `hterm` from consuming it. With that, our code (or Electron's code, depending on the accelerator) can consume it.

This is a temporary fix because in the near future we'll probably have a way to customize the accelerators via `.hyper.js`.

Closes #274; Closes #1025;

### CODE REVIEW

**Comment by rumpelsepp** [comment]
Works!

**Comment by roccomuso** [comment]
When will it be in a release? It's a key feature. >.>

**Comment by leo** [comment]
@roccomuso Comes with the next release

**Comment by jekku** [comment]
still not working with archlinux-kde

**Comment by rickmed** [comment]
was this added to 1.0? is not working in my ubuntu 16.04

**Pull request merged**
