### PR TITLE
Replace gaze with chokidar for config watcher

### LINKED ISSUE #1910: Something in hyper is trying to read my google drive folder
- [X] I am on the [latest](https://github.com/zeit/hyper/releases/latest) Hyper.app version
- [X] I have searched the [issues](https://github.com/zeit/hyper/issues) of this repo and believe that this is not a duplicate

- **OS version and name**: Windows 10 Enterprise 64bit Version 1703 build 15063.332
- **Hyper.app version**: 1.3.3
- **Link of a [Gist](https://gist.github.com/) with the contents of your .hyper.js**: https://gist.github.com/amiram/bc91a1c9cfd8a051d53a0f3cd864b169
- **Relevant information from devtools** _(CMD+ALT+I on Mac OS, CTRL+SHIFT+I elsewhere)_: N/A
- **The issue is reproducible in vanilla Hyper.app**: Hard to reproduce. Not sure.

## Issue

I just added google drive to my pc and suddenly I see a message box with this error every few minutes. Looks like hyper is messing with my personal folders.
The folder mentioned below is used by google drive for downloads. This is a temp folder so it can be removed sometimes. I guess that the error happens when the folder is removed.
Why hyper is looking at this folder?

A JavaScript error occurred in the main process

`Uncaught Exception:
Error: ENOENT: no such file or directory, lstat 'C:\Users\****\GoogleDrive\.tmp.drivedownload\tmpquykku.drivedownload'
    at Error (native)
    at fs.lstatSync (fs.js:982:18)
    at Object.fs.lstatSync (ELECTRON_ASAR.js:244:16)
    at Gaze._addToWatched (C:\Users\****\AppData\Local\hyper\app-1.3.3\resources\app\node_modules\gaze\lib\gaze.js:292:14)
    at Gaze._internalAdd (C:\Users\****\AppData\Local\hyper\app-1.3.3\resources\app\node_modules\gaze\lib\gaze.js:206:10)
    at C:\Users\****\AppData\Local\hyper\app-1.3.3\resources\app\node_modules\gaze\lib\gaze.js:419:16
    at Array.forEach (native)
    at C:\Users\****\AppData\Local\hyper\app-1.3.3\resources\app\node_modules\gaze\lib\gaze.js:415:12
    at FSReqWrap.oncomplete (fs.js:123:15)
`

### PR DESCRIPTION
**Pull request by albinekb**
Hopefully fix #1910

### CODE REVIEW

**Comment by matheuss** [comment]
@albinekb can you elaborate? How it would fix it?

**Comment by albinekb** [comment]
- gaze uses synchronous FS calls
- chokidar seems to be used more (webpack, rollup etc)
- gaze seems to have some bug with singe file watch (it's mostly made for glob watching)

**Comment by Stanzilla** [comment]
This should go in before a release, see https://github.com/zeit/hyper/pull/1960#issuecomment-311495901
@albinekb what is missing here before it can be merged?

**Comment by ppot** [comment]
@albinekb ?

**Comment by leo** [comment]
Just tested this locally on Windows with a friend and concluded that it's definitely needed. He's been using a custom build for some time now (based on this PR)...

**Pull request merged**
