### PR TITLE
Open Hyper config in the native desktop's default manner

### LINKED ISSUE #1529: Weird behaviour when opening config on Windows
- [x] I am on the [latest](https://github.com/zeit/hyper/releases/latest) Hyper.app version
- [x] I have searched the [issues](https://github.com/zeit/hyper/issues) of this repo and believe that this is not a duplicate

- **OS version and name**: Windows 8.1
- **Hyper.app version**: 1.2.1
- **Link of a [Gist](https://gist.github.com/) with the contents of your .hyper.js**: https://gist.github.com/Stanzilla/e776f86ed2b919fdfd7a2fc3d9d6de49
- **Relevant information from devtools** _(CMD+ALT+I on Mac OS, CTRL+SHIFT+I elsewhere)_: 
- **The issue is reproducible in vanilla Hyper.app**: 

## Issue

hyper_2017-02-16_19-10-00

When opening the config, a new tab is opened and gets a lot of echos, is this the correct behaviour? From the text it is looking like it's failing a few times but notepad is actually opened.

Should opening the config even spawn a new tab at all?

### PR DESCRIPTION
**Pull request by chabou**
This PR fixes #1529

It uses Electron API to open config file with OS default editor.
Bonus: Dev config file is opened if used.

We should test if no default app is set to open a `.js` file on MacOS/Windows/Linux

### CODE REVIEW

**Comment by ppot** [comment]
Tested and it open in atom since it's my default for Mac I think! Good.

**Comment by Stanzilla** [comment]
Now we've come full circle :D I think default without config option > config option though. You would have to keep a fallback to default anyway in case a user uninstalls his preferred editor. Also can't think of an app that lets you specify an another app to edit its config.

**Comment by chabou** [comment]
Maybe, it is not a good idea to have a `.js` suffix. `.hyper.config` could be better handled by OS.
If you want a specific app to edit it, you can open with this app directly. We don't need to specify it in config.

Our default behavior should be the OS one imo.

**Comment by MartyGentillon** [comment]
@ppot were you hoping that it might open it with a text editor in terminal mode?  Because that doesn't seem likely if we use the electron API.

But it does give me an idea for a plugin.  It might be nice to have a plugin that allows you to choose from a configurable list of commands and have Hyper type them directly into the console for you (sort of like shell aliases, but with fuzzy matching command finding goodness).  Then you could use that plugin to open the config when you want to do something different.

**Comment by MartyGentillon** [comment]
of course, you might be able to do something similar with peco....

**Comment by ppot** [comment]
The first step is renaming `.hyper.js` to `hyper.conf`

**Comment by albinekb** [comment]
Why change to `.conf` then my editor won't know it's JS @ppot

**Comment by ppot** [comment]
@albinekb Look better :crossed_fingers:

**Comment by toddself** [comment]
For some of us, we have set no default editor since our default editor is a terminal based application.

With my default windows setup, this tries to open ~/.hyper.js with Windows Script Host which is a really bad idea.

**Comment by Stanzilla** [comment]
@toddself What would you expect it to do in this case?

**Comment by Razzeee** [comment]
This is what happens then, btw
image

**Comment by toddself** [comment]
@stanzilla it should show me the "you need to choose a program to open this file with". 

Ideally what I would expect is that a menu option called "settings" opens up in an editor built into the program. My initial thought on this was that something was broken with hyper and it was supposed to be loading a module and showing me a dialog.

**Pull request merged**
