### PR TITLE
fix single tab title

### PR DESCRIPTION
**Pull request by nersoh**
Fix [#2148](https://github.com/zeit/hyper/issues/2148)

### CODE REVIEW

**Comment by rauchg** [comment]
Could you post a screenshot of before/after ?

**Comment by albinekb** [comment]
Just tested this branch, when you have a single title in a single tab, the title is no longer centered:
image

We need more padding to the right of the title when truncated
image

Otherwise correct 👍 
image
image

**Comment by nersoh** [comment]
@rauchg @albinekb I'll work on that, thanks.

**Comment by nersoh** [comment]
Single tab (Before)
screen shot 2017-09-29 at 1 47 32 am

Single tab (After)
screen shot 2017-09-29 at 1 45 41 am

Multiple tabs (No changes)
screen shot 2017-09-29 at 1 46 18 am

**Comment by MAPESO** [comment]
@rauchg @albinekb 
Windows 10
22207403_1149023835241205_289594526_n
Linux
tes

As you can see the version of Windows does not show the path as in the Linux and macOS.

**Comment by MAPESO** [comment]
Correctly reproduce the problem (double line for the title) but the results in Windows were different to the versions of macOS and linux.

**Comment by albinekb** [comment]
Thanks @nersoh 🎉

**Comment by nersoh** [comment]
It's my pleasure @albinekb 🎉 👏

**Pull request merged**
