### PR TITLE
Mac: altIsMeta support

### PR DESCRIPTION
**Pull request by saamalik**
* Reimplement altIsMeta supprt with new xterm library

_PR is ready to be merged _when_ underlying xterm.js is updated to this version: https://github.com/xtermjs/xterm.js/commit/616958e2c6c004133e4c5fe728702852bb1d2a5f. We just need to update the hyper xterm version in package.json._

Fixes: https://github.com/zeit/hyper/issues/2578

### CODE REVIEW

**Comment by saamalik** [comment]
The new _xterm_ option `macOptionIsMeta` was recently added in this PR: https://github.com/xtermjs/xterm.js/pull/1225

**Comment by chabou** [comment]
Amazing work @saamalik! You PR in `xterm` is awesome!
Thank you so much for your help 🙏

**Comment by albinekb** [comment]
Thank you and again awesome work @saamalik ❤️

**Comment by saamalik** [comment]
@albinekb my pleasure! Thank you for building and maintaining such an awesome terminal!

**Comment by MindTooth** [comment]
Hi,

Not sure if this is working as intended.  At least I can't managed to make it work with WeeChat.
Expected behaviour is that I can Alt + Up/Down to change buffers.  It only acts as regular up and down arrow keys, switches between previous commands.  This works when using the Command key however.  But that doesn't work with other combos since the key is used for other things on macOS.

I've set `altIsMeta: true`.

It works as intended when using iTerm2.app,   In Terminal.app only Alt + Up/Down works.

Any thoughts?  Is there any bindings in hyper.js that takes precedence?

Ref.keys: https://weechat.org/files/doc/devel/weechat_user.en.html#key_bindings_buffers_windows

**Comment by saamalik** [comment]
@MindTooth -- from the xterm.js code, I can see that `alt + up/down` is already supported even before this change. The changes introduced in the `xterm.js` PR were more for `alt + [a-z]` sequences. I'll try out the `alt + up/down` sequences later tonight to see if I can reproduce the issue.

**Comment by Logan2211** [comment]
I'm seeing a similar issue as @MindTooth... meta seems to be working for everything except up/down/left/right in tmux for me. `altIsMeta: true` is set.

**Comment by hozza** [comment]
@logan2211 same here `modifierKeys: { altIsMeta: true }` set inside `config` but not working with tmux over ssh.

**Pull request merged**
