### PR TITLE
Add github actions

### PR DESCRIPTION
**Pull request by LabhanshAgrawal**
Added test & build on windows, mac and linux with build artifact upload

### CODE REVIEW

**Comment by LabhanshAgrawal** [comment]
You can see a sample run [here](https://github.com/LabhanshAgrawal/hyper/runs/384730980)

**Comment by Stanzilla** [comment]
I like it! Would probably make every `name` entry in title case.

**Comment by LabhanshAgrawal** [comment]
> I like it! Would probably make every `name` entry in title case.

done

**Comment by Stanzilla** [comment]
@LabhanshAgrawal Just noticed, you didn't do the icon replacement when on canary stuff, https://github.com/zeit/hyper/blob/canary/appveyor.yml#L27 if we add that, I think we can remove appveyor and travis at least.

**Comment by LabhanshAgrawal** [comment]
Oh, I hadn't looked at appveyor or travis configs.
I'll add that.
I also noticed that since we have trigger on push and pull request, dependabot pr's are triggering double the jobs.
For that, will add a condition for push jobs to run only on master and canary

**Comment by Stanzilla** [comment]
Yup, that makes sense!

**Comment by LabhanshAgrawal** [comment]
> @LabhanshAgrawal Just noticed, you didn't do the icon replacement when on canary stuff, https://github.com/zeit/hyper/blob/canary/appveyor.yml#L27 if we add that, I think we can remove appveyor and travis at least.

Doesn't appveyor and travis also include the setup for releasing? So, shouldn't we keep them, to do any releases in future?

**Comment by Stanzilla** [comment]
Oh hrm, well I actually don't know how they did that. Just that they used `now release`

**Pull request merged**
