### PR TITLE
Fix update notification link

### LINKED ISSUE #2636: Update notification "Notes" link is probably wrong
- [x] I am on the [latest](https://github.com/zeit/hyper/releases/latest) Hyper.app version
- [x] I have searched the [issues](https://github.com/zeit/hyper/issues) of this repo and believe that this is not a duplicate

- **OS version and name**: macOS 10.13.2
- **Hyper.app version**: 2.0.0-canary.10

## Issue
For the last two (or more?) Canary updates, the URL of the `(notes)` link in the update notification...

... has pointed to the .zip of the release, triggering a download:

I suspect the intent was to link to the release page itself (for instance, https://github.com/zeit/hyper/releases/tag/2.0.0-canary.11), but the wrong link is being generated or entered.

### PR DESCRIPTION
**Pull request by ppot**
Update `releaseUrl` in a way that `updateUrl` don't override the `tag` url

close #2636

### CODE REVIEW

**Comment by Stanzilla** [comment]
@ppot nice! build failed because of a linting error btw:

```
C:\projects\hyper\lib\components\notifications.js
  83:13  error  Delete `··⏎············`  prettier/prettier
```

**Comment by ppot** [comment]
@Stanzilla Ya don't know how prettier work 😂

**Comment by Stanzilla** [comment]
@ppot `yarn run lint --fix` :D

**Comment by ppot** [comment]
Fixed

**Comment by albinekb** [comment]
👍

**Pull request merged**
