### PR TITLE
Add artifacts publishing on windows

### PR DESCRIPTION
**Pull request by vors**
Publish `Hyper Setup x.x.x.exe` file to AppVeyor artifacts tab.
This way, it's very easy to share recent windows builds with people.

It also would be nice to add appveyor build badge to the README.md, but only the admins on the appveyor projects can get the badge URL. https://www.appveyor.com/docs/status-badges/

### CODE REVIEW

**Comment by vors** [comment]
Artifacts tab: https://ci.appveyor.com/project/appveyor-zeit/hyper/build/1.0.67/artifacts

**Comment by vors** [comment]
Ping

**Comment by matheuss** [comment]
Yo @vors, thank you for the ping 😅 

Before we merge: Any idea on why our AppVeyor builds are failing? 😩 https://github.com/zeit/hyper/commits/add/ime

**Comment by vors** [comment]
@matheuss interesting. No cannot figure it out from the top of my head.
It could be that default worker image changed or something.
There is a way to **rdp** to the machine: https://www.appveyor.com/docs/how-to/rdp-to-build-worker/

**Comment by matheuss** [comment]
Thank you 😄 Will see if this continues to happen after we merge that branch.

**Pull request merged**
