### PR TITLE
fix echo issue in config pref

### PR DESCRIPTION
**Pull request by henrikdahl**
Fixes https://github.com/zeit/hyper/issues/1619 issue with echo being prepended to config pref ✌️

### CODE REVIEW

**Comment by henrikdahl** [comment]
Related https://github.com/zeit/hyper/issues/1626

**Comment by matheuss** [comment]
🙏 ❤️

**Comment by Stanzilla** [comment]
Even with 1.3.1 the echo appears twice 
hyper_2017-03-10_21-16-45

**Comment by henrikdahl** [comment]
@Stanzilla that wasn't the bug this merge approached ✌️

**Pull request merged**
