### PR TITLE
Changed "Close Session" shortcut so it doesn't have the same as "Quit"

### PR DESCRIPTION
**Pull request by louislva**
Fixed issue #2156

### CODE REVIEW

**Comment by chabou** [comment]
@phfontess `ctrl+tab` and `ctrl+shift+tab` will certainly be used to cycle between tabs like Chrome

**Comment by phfontess** [comment]
Oh I'm so sorry. I wanted to say only Ctrl + W, as it is used in version 1.3.3.

**Comment by louislva** [comment]
Ctrl+W for closing panes would be problematic as Ctrl is used as a character in most terminals including hyper. Lots of command line apps probably depend on Ctrl + W for their own shortcuts.

**Comment by chabou** [comment]
`ctrl+w` is used to delete word before cursor in bash/zsh
And agree with @louislva `ctrl+[a-z]` should be reserved to shell and command line programs.

**Comment by chabou** [comment]
Thank you so much @louislva

**Comment by louislva** [comment]
Thanks for letting me contribute! I've been wanting to get into OSS contributing for a while now, and the hyper community seems really friendly.

**Comment by chabou** [comment]
You are really welcome and we are proud to have your first OSS contribution 🙏

**Pull request merged**
