### PR TITLE
Adding logic to support working directory config

### PR DESCRIPTION
**Pull request by kaushikchaubal**

### CODE REVIEW

**Comment by chabou** [comment]
Thank you for your help.

Can you try [hyper-working-directory](https://www.npmjs.com/package/hyper-working-directory) plugin?
It seems to do what you need

**Comment by MandeeD** [comment]
FWIW, [hyper-working-directory](https://www.npmjs.com/package/hyper-working-directory) only opens new tabs in the specified working directory, rather than starting up in the working directory.

**Comment by Stanzilla** [comment]
Thank you for this!

**Comment by johnletey** [comment]
This doesn't work. When I have `workingDirectory: '~/dev/'` and `workingDirectory: '$HOME/dev/'`, Hyper still starts up in `~`.

I'm using `Hyper 3.0.1-canary.4 (canary)`

**Comment by LabhanshAgrawal** [comment]
> This doesn't work. When I have `workingDirectory: '~/dev/'` and `workingDirectory: '$HOME/dev/'`, Hyper still starts up in `~`.
> 
> I'm using `Hyper 3.0.1-canary.4 (canary)`

`// set custom startup directory (must be an absolute path)`

**Pull request merged**
