### PR TITLE
Add a shortcut to toggle fullscreen mode. Fix #1187

### LINKED ISSUE #1187: Add ability to toggle pane fullscreen
iTerm allows this when using command-shift-enter. Probably the thing I miss the most.

### PR DESCRIPTION
**Pull request by evanxd**
This pull request fixes #1187 .

Add a shortcut(`Super+Enter`) to toggle fullscreen mode.

Could you help review the patch? Thanks.

### CODE REVIEW

**Comment by tbodt** [comment]
What's Super?

**Comment by citycide** [comment]
@tbodt `super` is just a universal name for either the <kbd>Windows</kbd> key on Windows / Linux or the <kbd>Command</kbd> key on Mac.

**Comment by cthedot** [comment]
Normal keyboard shortcut for Fullscreen on Windows is F11 or sometimes ALT+ENTER too. WIN+ENTER toggles narrator and guess should not be replaced.
I have no idea how it works but is it possible to have OS specific and different keyboard shortcuts in Electron/Hyper?

**Comment by albinekb** [comment]
I think this should be configurable? cc: @matheuss

**Comment by matheuss** [comment]
I don't think it's a good idea to set a global shortcut like that 🤔 

Other than that, that's doable via a plugin, and as a recent policy we're not merging this kind of change (simple change, doable as a plugin) into the core codebase 🙌

**Comment by MEDIUM-ch** [comment]
I *do* think it's a good idea to set a global shortcut like that  ;)

More seriously, this is in the main menu so should have a Keyboard shortcut too and as it is common probably F11  (or/and maybe platform specific to Windows ALT+ENTER). A core functionality should be Keyboard accessible and be part of the core and not be implemented in a plugin.

**Pull request closed without merging**
