### PR TITLE
Add shell menu feature

### PR DESCRIPTION
**Pull request by Specro**
Adds right click 'Open Hyper here' shell menu feature on Windows. 

Open Hyper here

Depending on the shellMenu option in config it adds or removes the entries from the registry.

* Need tests on macOS and Linux to make sure it doesn't brake anything.
* Maybe a better name than shell menu?
* Add & remove methods have empty callbacks so far. Maybe returning something could be useful for notifications, etc.

### CODE REVIEW

**Comment by matheuss** [comment]
Amazing, @Specro 😄 

Maybe we could go option-less on this one 🤔 Do you think someone would like to disable this? It'd be annoying to not be able to disable it?

For the name: maybe `systemContextMenu` or something 🤔

**Comment by Specro** [comment]
I also thought the option wasn't necessary but left it just in case. Came close to that with `contextMenu` just couldn't figure out a modifier 😅 so there wouldn't be any confusion with terminal context menu. Thanks, gonna apply these with next commit :smile:

**Comment by levrik** [comment]
Could you please ensure that the menu item gets removed on uninstall of Hyper? Would be annoying to remove it manually after an uninstall.

**Comment by matheuss** [comment]
That's a good catch, @levrik. I think that to accomplish that, we'll have to handle the Squirrel command for uninstall 🤔

**Comment by Specro** [comment]
I rewrote this to add/remove the context menu during installation/uninstallation. Seems to work fine 😃

**Comment by matheuss** [comment]
Perfect, thank you! 😄

**Pull request merged**
