### PR TITLE
No string refs

### PR DESCRIPTION
**Pull request by maxdeviant**
This PR removes the one instance of a string ref, and re-enables the xo rule to check for them, as per #730.

### CODE REVIEW

**Comment by rauchg** [comment]
Is this the only string ref we have?

**Comment by maxdeviant** [comment]
@rauchg Surprisingly, yes! It's the only one `xo` caught, and I also just ran a search for `this.refs` and it was the only one.

**Comment by leo** [comment]
@maxdeviant Please resolve the conflicts!

**Comment by maxdeviant** [comment]
@leo Resolved :tada:

**Comment by leo** [comment]
Thanks! 😘

**Pull request merged**
