### PR TITLE
fix Linux AppImage download link

### PR DESCRIPTION
**Pull request by thephilip**
Refers to issue #1636.

### CODE REVIEW

**Comment by albinekb** [comment]
Nice

**Comment by albinekb** [comment]
@matheuss we should set up a small `now` deployment that's a static URL to the latest release maybe? so a deploy of the website is not necessary when we release a new version?
like: https://latest-hyper.now.sh/linux

**Comment by thephilip** [comment]
You're very welcome, @albinekb.  Thanks for the great application.

**Comment by benjamin-rood** [comment]
FYI still getting a 404 on https://latest-hyper.now.sh/linux

**Comment by albinekb** [comment]
It's now http://hyper-latest.now.sh @benjamin-rood source is here: https://github.com/zeit/hyper-latest :)

**Pull request merged**
