### PR TITLE
[Hyper-cli] Add cli cmd

### PR DESCRIPTION
**Pull request by chabou**
Replace #2337 

DO NOT MERGE IT. This feature was created to make review easier.
This PR is already merged in #2375 branch (the only one that should be merged).

* Hyper CLI javascript file is bootstrapped by scripts (located in `build/(mac|win|linux)/`)
* Right platform script(s) are copied at build time to `resources/bin/`
* When installing Hyper on Linux, platform script is symlinked to `/usr/local/bin`.
* At Hyper startup time (only in production mode), platform script is symlinked to `/usr/local/bin` on Mac, or `resources/bin` is added to user PATH env var on Windows.

### CODE REVIEW

**Comment by chabou** [comment]
There is a caveat with Windows.

I correctly add hyper bin path to user path. But there is some cache mechanism. User should go to "Modify user env var" dialog and just hit ok button (or reboot his computer :trollface: )

**Comment by chabou** [comment]
There is an error on Linux
```
Failed to symlink Hyper CLI { Error: EACCES: permission denied, unlink '/usr/local/bin/hyper'
  errno: -13,
  code: 'EACCES',
  syscall: 'unlink',
  path: '/usr/local/bin/hyper' }
```

```
parallels@ubuntu:~/hyper$ ls -lah /usr/local/bin/
total 8.0K
drwxr-xr-x  2 root root 4.0K Oct 23 00:02 .
drwxr-xr-x 10 root root 4.0K Jul 19  2016 ..
lrwxrwxrwx  1 root root   16 Oct 23 00:02 hyper -> /opt/Hyper/hyper
```
I don't think that `electron-builder` can execute postinstall scripts.

I don't know how to resolve this.
Possible workaround:
* rename Hyper CLI command to `hyper-cli` or `hpm` or `hyperctl`
* Embed CLI handling directly in Hyper (but deal with unique app instance restriction)

Any thought @rauchg @leo @Qix- @albinekb @CodeTheory @Stanzilla @derrickpelletier ?

**Comment by Stanzilla** [comment]
I kinda liked `hpm`, my other idea was more of a joke but we could use a unicode symbol in the app name 😸

**Comment by chabou** [comment]
I was wrong! I found how to execute postinstall script with electron-builder 🎉 🎉 🎉 
See [afterInstall option](https://www.electron.build/configuration/linux).

**Comment by chabou** [comment]
Merged with #2375

**Pull request closed without merging**
