### PR TITLE
Hide header when no tabs

### PR DESCRIPTION
**Pull request by dkkoval**
Before:
before
After:
after

### CODE REVIEW

**Comment by CodeTheory** [comment]
I'm not sure this will work because of Mac OS. Me or someone else will test it soon.

**Comment by danprince** [comment]
Already been through this once on https://github.com/zeit/hyper/pull/232. The end result was the decision to push this out to a plugin.

If this landed in the hyper codebase, then it'd need some conditionals to handle OSX, which puts the tabs directly into the title bar.

screen shot 2016-10-18 at 18 31 30

**Comment by dkkoval** [comment]
OK, thanks man

**Comment by danprince** [comment]
I put together [danprince/hypertile](https://github.com/danprince/hypertile) to make hyperterm more usable for tiling window managers, by removing tabs, titles and window decorations altogether. Looks like you're using a tiling window manager, so you might find it useful.

**Comment by rauchg** [comment]
@danprice that's a great solution

**Comment by rauchg** [comment]
That said, optimizations for the look n feel of Windows / Linux are coming. Stay tuned!

**Pull request closed without merging**
