### PR TITLE
Add support for cursor styles 5 and 6 to hterm

### LINKED ISSUE #270: Vim (neovim) cursor shape does not change (BLOCK to VLINE shape).
On the terminal itself the cursor works fine and changes to BLOCK shape to VLINE shape but inside VIM its simple does not work.

Follow my configuration for the cursor shape on my .zshrc file:

```
        vicmd)      print -n -- "\E]50;CursorShape=0\C-G";;  # block cursor
        viins|main) print -n -- "\E]50;CursorShape=1\C-G";;  # line cursor

```

I've try all different bellow configurations on VIM without success:
http://stackoverflow.com/questions/6488683/how-do-i-change-the-vim-cursor-in-insert-normal-mode
http://vim.wikia.com/wiki/Change_cursor_shape_in_different_modes

For example, I can change the shape on iTerm2/VIM with the follow setup:

```
let $NVIM_TUI_ENABLE_CURSOR_SHAPE=1
let &t_SI = "\<Esc>]50;CursorShape=1\x7"
let &t_SR = "\<Esc>]50;CursorShape=2\x7"
let &t_EI = "\<Esc>]50;CursorShape=0\x7"
```

Appreciate any help at all.

Thanks!

### PR DESCRIPTION
**Pull request by tbodt**
This fixes #270, cursor shape changing in Neovim.

### CODE REVIEW

**Comment by colepeters** [comment]
This looks awesome, thanks for your work on this @tbodt. Can’t wait to try it out. This has been one of the things stopping me from making the full switch from iTerm to Hyper.

**Comment by tbodt** [comment]
There are a number of other styling things I'd like to fix, such as underline/i-beam cursors not blinking, but the root cause is hterm. SO CAN WE PLEASE FOR THE LOVE OF GOD USE A JAVASCRIPT TERMINAL LIBRARY THAT DOES NOT REQUIRE SIGNING AN NDA TO CONTRIBUTE TO!!! #1275

**Comment by babenzele** [comment]
@tbodt I can only find reference to changing the cursor permanently from within `hyper.js`. 

```javascript
module.exports = {
  cursorShape: 'BLOCK'
}
```

But do you know how one would trigger this from vim, such that it is BEAM in Insert mode and BLOCK in Normal mode?

**Comment by colepeters** [comment]
@babenzele Not sure if possible in Vim, but for Neovim, drop this in your `init.vim`:

```vimL
let $NVIM_TUI_ENABLE_CURSOR_SHAPE=1	" Cursor is pipe in Insert, block in Normal
```

**Comment by tbodt** [comment]
It certainly is possible in Vim:

    let &t_SI = "\<Esc>]50;CursorShape=1\x7"
    let &t_EI = "\<Esc>]50;CursorShape=0\x7"

~Theodore

**Comment by vapier** [comment]
FTR, hterm has never required a NDA and never will.  an NDA doesn't even make sense when the project is open source.

**Comment by tbodt** [comment]
...I think I meant CLA...I swear I saw NDA somewhere though.

**Comment by vapier** [comment]
then i don't understand your complaint.  yes, hterm has a CLA, but xterm.js also has a CLA.  you have read their CONTRIBUTING.md right ?

**Comment by albinekb** [comment]
Problem with hterm is that it's not on github @vapier @tbodt, makes it really hard to contribute and the effort to set it all up and learn the whole system google has just isn't worth it, that's why we were maintaining all of these hot-patches over hterm. Not an issue anymore with xterm 👌

**Comment by vapier** [comment]
this was only talking about @tbodt's claim about NDA/CLA

**Pull request merged**
