### PR TITLE
Adding in ability to switch release channel without restarting Hyper

### PR DESCRIPTION
**Pull request by KevinRLeC**
This is to address #2351 

This code seems to run properly. However, it is difficult to fully test without a Mac Developer ID. I didn't realize that these licenses require a yearly subscription ☹️. So far if I try to build this as a package and change the `autoUpdater` channel I receive errors that the app is not code-signed. If someone with one of these licenses could give this a quick test that would be great!

### CODE REVIEW

**Comment by qkdreyer** [comment]
I've successfully managed to build your fork using **yarn run dist**, and here is the output from running the fresly compiled Hyper.app :

```
TRIOMBP:hyper qkdreyer$ ./dist/mac/Hyper.app/Contents/MacOS/Hyper 
Plugin hyper-transparent (1.1.3) loaded.
Plugin hyper-startup (0.2.0) loaded.
Plugin hypercwd (1.1.1) loaded.
running in prod mode
electron will open file:///Users/qkdreyer/Projects/hyper/dist/mac/Hyper.app/Contents/Resources/app.asar/index.html
2017-11-08 10:21:52.757 Hyper[13220:2818107] *** WARNING: Textured window <AtomNSWindow: 0x7ff42cef3d20> is getting an implicitly transparent titlebar. This will break when linking against newer SDKs. Use NSWindow's -titlebarAppearsTransparent=YES instead.
Checking for notification messages
No matching notification messages
2017-11-08 10:22:11.480 Hyper[13220:2818113] Download completed to: file:///Users/qkdreyer/Library/Caches/co.zeit.hyper.ShipIt/update.07cYpjp/hyper-2.1.1-mac.zip
Error fetching updates Code signature at URL file:///Users/qkdreyer/Library/Caches/co.zeit.hyper.ShipIt/update.07cYpjp/Hyper.app/ did not pass validation: le code n’est pas conforme aux exigences de code spécifiées (Error: Code signature at URL file:///Users/qkdreyer/Library/Caches/co.zeit.hyper.ShipIt/update.07cYpjp/Hyper.app/ did not pass validation: le code n’est pas conforme aux exigences de code spécifiées)
```

**Comment by chabou** [comment]
@KevinRLeC Thank you so much for this PR 🙏 

Indeed this is really hard to test this type of feature. Mac Developer ID is not enough. Only Zeit certificate can sign this application. But I think that `canary` commit CI builds are signed. 

Your code seems OK. What we can do is to merge your code into `canary` in order to have a signed version with your PR and test it: setting `canaryChannel` to `'stable'` should directly check update and ask to install.

**Comment by chabou** [comment]
Tested with signed artefact generated by CircleCI.
I edited `Hyper.app` to fake its version number.
After editing config, it has directly downloaded canary release 😍 

Really good job @KevinRLeC

**Comment by KevinRLeC** [comment]
Glad it worked @chabou keep up the great work with the product 😄

**Pull request merged**
