### PR TITLE
Enable preliminary Windows support

### PR DESCRIPTION
**Pull request by kwonoj**
This PR consists couple of changes to enable preliminary support on Windows platform, by
- replace `child_pty` to `ptyw.js`
  : original module `pty` currently have known issues with windows build (https://github.com/chjj/pty.js/issues/131), introduced `ptyw` until issue's fully resolved.
- add initial configuration to `appveyor` to trigger windows build.
  : currently only install dependenceis / bulid native modules, does not packaging it yet.
  : resues existing install script (`install.sh`), so anyone want to build locally may require *nix shell environment still.

As this PR replaces one of core module, I agree this can be risky change especially there isn't enough test coverage. Please feel freely reject if this need not to be considered at this moment.

### CODE REVIEW

**Comment by rauchg** [comment]
@gottox is `child_pty` not working on Windows? Based on a quick look of the code of both `pty.js` and `child_pty`, I would like to retain the latter.

Awesome stuff so far!

**Comment by Gottox** [comment]
child_pty does only work on unix systems atm. There were some experiments with [winpty](https://github.com/rprichard/winpty) but as I don't own a windows system to test it hasn't come that far yet.

**Comment by Gottox** [comment]
The main problem with winpty is that I refuse to ship winpty in binary.

winpty itself has insane build deps, requiring both, a [cygwin and a MinGW](https://github.com/rprichard/winpty#cygwinmsys-adapter-winptyexe) toolchain.

So for now I decided to keep it simple and only support unix systems.

**Comment by Gottox** [comment]
I'm currently playing with a windows VM and nodejs. I let you know if I get it up and running.

**Comment by ingro** [comment]
@Gottox looking forward to this!

**Comment by Gottox** [comment]
See ongoing process here: https://github.com/Gottox/child_pty/tree/windows

**Comment by mablae** [comment]
I am just totally thrilled since I if the windows build hyperterm will be able to attach to the terminal panel
inside IntelliJ IDEA IDE ?

**Comment by Gottox** [comment]
This will take some time, I guess. winpty is quite different from the unix API... Especially I can't reuse child_process on windows, so a lot of stuff needs to be written. In order to get hyperterm on windows out fast, I guess switching back to pty.js is a better solution.

**Comment by rauchg** [comment]
Thanks for the update @Gottox. One thing I'd like to check before we temporarily switch back to this is: chatting with @Tyriar he shared some concerns about `pty.js` leaking memory when bundled with Electron. Therefore what we need in order to merge this is to answer:

- Is this still the case?
- Is it the case for pty*w*.js?
- Are there any other differences with `child_pty` we're not contemplating?

**Comment by Tyriar** [comment]
The main issue with pty.js is that it must by run in a child process on OS X or it maxes out the CPU, see https://github.com/electron/electron/issues/38

The current situation with vscode is that we do just that, but we don't use chjj/pty.js, instead we my personal fork of it Tyriar/pty.js which is a fork itself:

```
Tyriar/pty.js -> platformio/pty.js -> jeremyramin/pty.js -> chjj/pty.js
```

The purpose of the Tyriar/ fork is to gets it building on new node (which ptyw.js seems to do) and working with our build system (by removing prebuilt assets). I'm passively looking around for a maintained alternative that uses a newer version of winpty.

**Comment by Gottox** [comment]
@rauchg

pty.js has some issues with binding of functions. So `this` points to unexpected objects. Other than that, I can't say much about pty.js. :)

**Comment by mablae** [comment]
Hey, 
instead of having two different pty libraries from now on, it would be better to solve the issues in child_pty upstream and make it usable with windows. These issues should be solved upstream. 

There are alreay many forks of child_pty. Also some guys work on windows. 
The debt a second pty would introduce in the project should be considered.

**Comment by Gottox** [comment]
Where are these windows forks your talking about? :)

**Comment by Adam-Meisen** [comment]
If there's any grunt work a newcomer to the project can do to help this along, let me know.

**Comment by tyrbo** [comment]
I'd love to help, but I'm not sure what's needed here.

**Comment by Gottox** [comment]
@tyrbo child_pty needs windows support. There's a [window branch](https://github.com/rprichard/winpty) in the child_pty repo. the branch includes the winpty project, but I haven't figured out how to intergrate it into child_pty. The hardest part is that winpty _needs_ a custom exec method, so we cannot use child_process directly.

**Comment by iamstarkov** [comment]
can anybody share status of this issue/pr?

**Comment by rvion** [comment]
@iamstarkov I think windows support is coming here: https://github.com/zeit/hyper/pull/946

**Comment by iamstarkov** [comment]
@rvion thanks.

this PR can be closed then? /cc @kwonoj

**Comment by kwonoj** [comment]
Yes, I'm closing this on behalf of #946. Wish this could make it, but those PR seems much more ready-to-ship state.

**Pull request closed without merging**
